(function (SA) {
  'use strict';
  var C = SA.Config, R = SA.Rules, W = SA.World, P = SA.Progression;
  var app = { state: SA.State.create(), renderer: null, accumulator: 0, last: 0, pausedByPanel: false, hudCache: {} };
  SA.app = app;
  function el(id) { return document.getElementById(id); }
  function start(seed) { app.state = SA.State.create(seed); app.state.mode = 'playing'; app.accumulator = 0; app.hudCache = {}; closePanels(); showGame(); W.notice(app.state, '应急系统上线。先采集铁与生物质，建造炮塔。'); updateHUD(); }
  function continueGame() { var s = SA.Save.load(); if (!s) return start(); app.state = s; app.hudCache = {}; if (s.mode === 'paused') s.mode = 'playing'; closePanels(); showGame(); updateHUD(); if (s.mode === 'victory' || s.mode === 'defeat') finish(s.mode); }
  function showGame() { el('title').hidden = true; el('end-screen').hidden = true; el('hud').hidden = false; el('game').hidden = false; if (app.renderer) app.renderer.resize(); }
  function showTitle() { closePanels(); app.state.mode = 'title'; el('title').hidden = false; el('end-screen').hidden = true; el('hud').hidden = true; el('game').hidden = true; el('continue-btn').disabled = !SA.Save.exists(); }
  function dispatch(kind, key) {
    var s = app.state; if (s.mode === 'title' || s.mode === 'victory' || s.mode === 'defeat') return;
    if (kind === 'cancel' || key === 'escape') { if (!el('pause').hidden) togglePause(); else if (panelOpen()) closePanels(); else if (s.mode === 'paused' || s.mode === 'playing') togglePause(); return; }
    if (panelOpen()) return;
    if (key >= '1' && key <= '5') { W.selectTool(s, C.tools[Number(key) - 1].id); updateHUD(); }
    else if (key === 'g') { s.scanIndex = (s.scanIndex + 1) % C.scanTypes.length; updateHUD(); }
    else if (key === 'f') W.usePlant(s);
    else if (key === 'q') P.useKit(s);
    else if (key === 't') openPanel('serum-panel');
    else if (key === 'b') openPanel('build-panel');
    else if (key === 'x') SA.Buildings.recycle(s);
    else if (key === 'u') SA.Buildings.upgrade(s);
    else if (key === 'y') SA.Buildings.unlock(s);
    else if (key === 'p') saveWithFeedback(s);
  }
  function togglePause() { var s = app.state; if (s.mode !== 'playing' && s.mode !== 'paused') return; s.mode = s.mode === 'paused' ? 'playing' : 'paused'; el('pause').hidden = s.mode !== 'paused'; SA.Input.clear(); }
  function panelOpen() { return !!document.querySelector('.modal:not([hidden])'); }
  function openPanel(id) { closePanels(); el(id).hidden = false; app.pausedByPanel = app.state.mode === 'playing'; app.state.mode = 'paused'; SA.Input.clear(); updatePanels(); }
  function closePanels() { document.querySelectorAll('.modal').forEach(function (x) { x.hidden = true; }); if (app.pausedByPanel && app.state.mode === 'paused') app.state.mode = 'playing'; app.pausedByPanel = false; }
  function saveWithFeedback(s) { var ok = SA.Save.save(s); W.notice(s, ok ? '进度已保存。' : '保存失败：浏览器存储不可用或空间不足。'); return ok; }
  function step(dt) {
    var s = app.state; if (s.mode !== 'playing') return;
    s.time += dt; s.notices.forEach(function (n) { n.time -= dt; }); s.notices = s.notices.filter(function (n) { return n.time > 0; });
    if (!s.forcedNight) { s.phaseTime += dt; var duration = s.isNight ? C.world.night : C.world.day; if (s.phaseTime >= duration) { s.phaseTime -= duration; s.isNight = !s.isNight; if (s.isNight) SA.Combat.spawn(s, Math.min(C.runtime.normalNightWaveCap, C.runtime.normalNightWaveBase + s.day * C.runtime.normalNightWavePerDay)); else { s.day += 1; W.dailySupply(s); SA.Save.save(s); } } }
    var held = SA.Input.state.held, dx = (held.d || held.arrowright ? 1 : 0) - (held.a || held.arrowleft ? 1 : 0), dy = (held.s || held.arrowdown ? 1 : 0) - (held.w || held.arrowup ? 1 : 0), sprint = !!held.shift;
    if (s.player.alive) { var zone = R.zoneAt(s.player.x, s.player.y), speed = C.player.speed * R.zoneSpeed(s, zone) * R.weightSpeed(s.inventory) * (sprint ? C.player.sprint : 1); if (dx || dy) { var length = Math.hypot(dx, dy); s.player.x = R.clamp(s.player.x + dx / length * speed * dt, 15, C.world.width - 15); s.player.y = R.clamp(s.player.y + dy / length * speed * dt, 15, C.world.height - 15); } var safe = R.distance(s.player, s.base) < C.base.oxygenRadius || s.buildings.some(function (b) { return b.hp > 0 && b.type === 'o2_station' && R.distance(s.player, b) < C.buildings.o2_station.range; }); if (safe) s.player.oxygen = Math.min(C.player.oxygen, s.player.oxygen + C.player.safeRecharge * dt); else s.player.oxygen -= C.player.baseDrain * R.zoneOxygen(s, zone) * R.weightOxygen(s.inventory) * (sprint ? C.player.sprintOxygenMultiplier : 1) * dt; if (s.player.oxygen <= 0) { s.player.oxygen = 0; R.die(s); } s.player.invulnerable = Math.max(0, s.player.invulnerable - dt); W.collectNearby(s); } else { s.player.respawn -= dt; if (s.player.respawn <= 0) R.respawn(s); }
    handleMouse(s); SA.Buildings.tick(s, dt); SA.Combat.tick(s, dt); if (s.mode !== 'defeat') P.tick(s, dt); if (s.mode === 'playing' && s.signal.extractionActive && s.enemies.length < C.signal.evacuationEnemyThreshold && s.signal.evacuationSpawnCooldown <= 0) { SA.Combat.spawn(s, C.signal.evacuationSpawnCount); s.signal.evacuationSpawnCooldown = C.signal.evacuationSpawnCooldown; } if (s.mode === 'victory' || s.mode === 'defeat') finish(s.mode); SA.Input.finishStep();
  }
  function handleMouse(s) { if (!s.player.alive) return; var m = SA.Input.state.mouse, point = app.renderer.worldPoint(m); if (s.tool === 'weapon' && m.down && (!s.lastShot || s.time - s.lastShot >= C.runtime.shotCooldown)) { SA.Combat.shoot(s, point); s.lastShot = s.time; } else if (m.pressed) { if (s.tool === 'harvester') W.harvest(s, point); else if (s.tool === 'scanner') W.scan(s); else if (s.tool === 'build') SA.Buildings.place(s, point); else if (s.tool === 'repair') SA.Buildings.repair(s, point); } }
  function finish(mode) { el('end-screen').hidden = false; el('end-title').textContent = mode === 'victory' ? '撤离成功' : '基地失守'; el('end-copy').textContent = mode === 'victory' ? '救援艇已穿过风暴。未领取缓存仍保留在本局记录中。' : '可以从新游戏重新建立防线。'; SA.Save.save(app.state); }
  function frame(t) { if (!app.last) app.last = t; app.accumulator = Math.min(C.runtime.maxFrameDelta, app.accumulator + (t - app.last) / 1000); app.last = t; while (app.accumulator >= C.step) { step(C.step); app.accumulator -= C.step; } if (app.state.mode !== 'title') { app.renderer.draw(app.state); updateHUD(); } requestAnimationFrame(frame); }
  function directionTo(s, target) { var dx = target.x - s.player.x, dy = target.y - s.player.y, angle = Math.atan2(dy, dx) * 180 / Math.PI, directions = ['北', '东北', '东', '东南', '南', '西南', '西', '西北']; return directions[Math.round(angle / 45 + 8) % 8]; }
  function scanStatus(s) { var target = W.scanTarget(s), nextLabel = W.scanLabel(C.scanTypes[s.scanIndex]), typeLabel = s.scanType ? W.scanLabel(s.scanType) : ''; if (!s.scanActive) return '扫描导航：关闭 · G 选择下一次扫描类别：' + nextLabel; if (!target) return '扫描导航：开启 · ' + typeLabel + ' · 暂无锁定目标 · G 选择下一次扫描类别：' + nextLabel; return '扫描导航：开启 · ' + typeLabel + ' · 锁定 ' + (target.type ? W.scanLabel(target.type) : typeLabel) + ' · ' + directionTo(s, target) + ' ' + Math.round(R.distance(s.player, target)) + 'm' + (target.underground ? ' · 地下 DIG' : '') + ' · G 选择下一次扫描类别：' + nextLabel; }
  function upgradeStatus(s) { var b = SA.Buildings.nearestTurret(s, s.player, C.runtime.turretUpgradeRange), cost = C.turretUpgrade.cost; if (!b || b.type !== 'turret') return '升级：靠近炮塔 ' + C.runtime.turretUpgradeRange + 'm 内可查看 U 升级成本。'; if (b.level >= C.turretUpgrade.max) return '炮塔升级：Lv' + b.level + ' · 已满级'; return '炮塔升级：Lv' + b.level + ' · 成本 ' + R.costText(cost) + ' · ' + (R.has(s.inventory, cost) ? 'ready' : '缺少 ' + Object.keys(cost).filter(function (k) { return (s.inventory[k] || 0) < cost[k]; }).map(function (k) { return C.resources[k].label + ' ' + (cost[k] - (s.inventory[k] || 0)); }).join(' / ')); }
  function updateHUD() { var s = app.state, zone = R.zoneAt(s.player.x, s.player.y), zd = C.zones[zone], load = R.weight(s.inventory); setText('o2-value', Math.ceil(s.player.oxygen) + ' / ' + C.player.oxygen); setStyle('o2-fill', 'width', (100 * s.player.oxygen / C.player.oxygen) + '%'); setText('hp-value', Math.ceil(s.player.hp) + ' / ' + C.player.hp); setText('base-value', Math.ceil(s.base.hp) + ' / ' + C.base.hp + (s.base.shield ? ' + 护盾 ' + Math.ceil(s.base.shield) : '')); setText('zone', zd.label + ' | 氧耗 x' + R.zoneOxygen(s, zone).toFixed(2) + ' | 适应 Lv' + s.adaptations[zone] + (zd.recommend ? ' / 建议 Lv' + zd.recommend + '+' : '')); setText('cycle', s.signal.extractionActive ? '撤离坚守 ' + P.format(s.signal.extractionRemaining) : '第 ' + s.day + ' 天 · ' + (s.isNight ? '夜袭' : '白天') + ' ' + Math.ceil((s.isNight ? C.world.night : C.world.day) - s.phaseTime) + 's'); setText('signal', '信号 ' + s.signal.progress + '%'); setText('objective', P.objective(s)); setText('weight', '负重 ' + load.toFixed(1) + ' / ' + C.player.capacity + ' kg' + (load > C.player.capacity ? '（超重软惩罚）' : '')); setHTML('inventory', Object.keys(C.resources).map(function (k) { return '<span>' + C.resources[k].label + ' ' + s.inventory[k] + '</span>'; }).join('')); setHTML('notices', s.notices.map(function (n) { return '<li>' + n.text + '</li>'; }).join('')); setHTML('radio-log', (s.signal.log || []).slice().reverse().map(function (line) { return '<li>' + line + '</li>'; }).join('')); setText('scan', scanStatus(s)); setText('upgrade', upgradeStatus(s)); document.querySelectorAll('[data-tool]').forEach(function (b) { b.classList.toggle('active', b.dataset.tool === s.tool); }); }
  function setText(id, value) { if (app.hudCache[id] === value) return; app.hudCache[id] = value; el(id).textContent = value; }
  function setHTML(id, value) { if (app.hudCache[id] === value) return; app.hudCache[id] = value; el(id).innerHTML = value; }
  function setStyle(id, property, value) { var key = id + ':' + property; if (app.hudCache[key] === value) return; app.hudCache[key] = value; el(id).style[property] = value; }
  function updatePanels() { var s = app.state; el('build-list').innerHTML = C.buildOrder.map(function (id) { var d = C.buildings[id]; return '<button data-build="' + id + '"' + (!s.unlocked[id] ? ' class="locked"' : '') + '><b>' + d.label + '</b><small>' + R.costText(d.cost) + (s.unlocked[id] ? '' : ' · 未解锁') + '</small></button>'; }).join(''); el('serum-list').innerHTML = Object.keys(C.zones).map(function (z) { var level = s.adaptations[z], recipe = C.serumRecipes[z][level]; return '<button data-serum="' + z + '"><b>' + C.zones[z].label + ' Lv' + level + '</b><small>' + (recipe ? '下一等级：' + R.costText(recipe) : '已达 Lv4') + '</small></button>'; }).join(''); }
  function wire() { app.renderer = new SA.Renderer(el('game')); window.addEventListener('resize', function () { app.renderer.resize(); }); SA.Input.install(el('game'), dispatch); el('new-btn').onclick = function () { if (!SA.Save.exists() || confirm('开始新游戏会覆盖当前单槽存档，继续吗？')) { SA.Save.remove(); start(); } }; el('continue-btn').onclick = continueGame; el('delete-btn').onclick = function () { if (confirm('删除单槽存档？')) { SA.Save.remove(); showTitle(); } }; el('save-btn').onclick = function () { saveWithFeedback(app.state); }; el('pause-btn').onclick = togglePause; el('resume-btn').onclick = togglePause; el('serum-btn').onclick = function () { openPanel('serum-panel'); }; el('build-btn').onclick = function () { openPanel('build-panel'); }; el('restart-btn').onclick = function () { SA.Save.remove(); start(); }; el('title-btn').onclick = showTitle; el('kit-btn').onclick = function () { P.useKit(app.state); }; el('craft-kit-btn').onclick = function () { P.craftKit(app.state); updatePanels(); }; document.addEventListener('click', function (e) { var b = e.target.closest('[data-tool],[data-build],[data-serum],[data-close]'); if (!b) return; if (b.dataset.tool) W.selectTool(app.state, b.dataset.tool); if (b.dataset.build) { app.state.buildSelection = b.dataset.build; W.selectTool(app.state, 'build'); closePanels(); } if (b.dataset.serum) { P.craftSerum(app.state, b.dataset.serum); updatePanels(); } if (b.dataset.close !== undefined) { if (b.closest('#pause')) togglePause(); else closePanels(); } updateHUD(); }); document.addEventListener('visibilitychange', function () { if (document.hidden && app.state.mode === 'playing') SA.Save.save(app.state); }); showTitle(); requestAnimationFrame(frame); }
  window.__STAR_ABYSS_TEST__ = { startNewGame: function (seed) { start(seed); return snapshot(); }, snapshot: snapshot, advance: function (seconds) { var count = Math.min(C.runtime.maxTestSteps, Math.ceil(seconds / C.step)); for (var i = 0; i < count; i += 1) step(C.step); return snapshot(); }, setState: function (patch) { applyPatch(app.state, patch || {}); updateHUD(); return snapshot(); }, save: function () { return SA.Save.save(app.state); }, load: function () { continueGame(); return snapshot(); } };
  function snapshot() { var s = app.state; return JSON.parse(JSON.stringify({ mode: s.mode, day: s.day, isNight: s.isNight, player: s.player, base: s.base, inventory: s.inventory, adaptations: s.adaptations, unlocked: s.unlocked, buildings: s.buildings, enemies: s.enemies, signal: s.signal, deathDrop: s.deathDrop, tool: s.tool, buildSelection: s.buildSelection })); }
  function applyPatch(target, patch) { Object.keys(patch).forEach(function (k) { if (patch[k] && typeof patch[k] === 'object' && !Array.isArray(patch[k]) && target[k] && typeof target[k] === 'object' && !Array.isArray(target[k])) applyPatch(target[k], patch[k]); else if (Object.prototype.hasOwnProperty.call(target, k)) target[k] = JSON.parse(JSON.stringify(patch[k])); }); }
  document.addEventListener('DOMContentLoaded', wire);
}(window.StarAbyss = window.StarAbyss || {}));
