(function (SA) {
  'use strict';
  var C = SA.Config, R = SA.Rules, W = SA.World, P = SA.Progression, G = SA.Guide;
  var app = { state: SA.State.create(), renderer: null, accumulator: 0, last: 0, pausedByPanel: false, guidePage: 0, pendingBuild: null, pendingSaveRename: null, hudCache: {} };
  SA.app = app;
  function el(id) { return document.getElementById(id); }
  function start(seed) { app.state = SA.State.create(seed); app.state.mode = 'playing'; app.accumulator = 0; app.hudCache = {}; closePanels(); showGame(); W.notice(app.state, '应急系统上线。先采集铁与生物质，建造炮塔。'); updateHUD(); }
  function applyLoadedState(s, feedback) { if (!s) return false; app.state = s; app.hudCache = {}; if (s.mode === 'paused') s.mode = 'playing'; closePanels(); showGame(); if (feedback) W.notice(s, feedback); updateHUD(); if (s.mode === 'victory' || s.mode === 'defeat') finish(s.mode); return true; }
  function continueGame(showFeedback) { var s = SA.Save.load(); if (!s) return start(); applyLoadedState(s, showFeedback ? '已读取自动存档：建筑 ' + s.buildings.length + '。' : ''); }
  function showGame() { el('title').hidden = true; el('end-screen').hidden = true; el('hud').hidden = false; el('game').hidden = false; if (app.renderer) app.renderer.resize(); }
  function showTitle() { closePanels(); app.state.mode = 'title'; el('title').hidden = false; el('end-screen').hidden = true; el('hud').hidden = true; el('game').hidden = true; el('continue-btn').disabled = !SA.Save.exists(); }
  function dispatch(kind, key) {
    var s = app.state; if (s.mode === 'title' || s.mode === 'victory' || s.mode === 'defeat') return;
    if (kind === 'cancel' || key === 'escape') { if (!el('pause').hidden) togglePause(); else if (panelOpen()) { if (!el('build-confirm-panel').hidden) cancelBuild(); else if (!el('save-rename-panel').hidden) cancelSaveRename(); else closePanels(); } else if (s.mode === 'paused' || s.mode === 'playing') togglePause(); return; }
    if (panelOpen()) return;
    if (key >= '1' && key <= '5') { W.selectTool(s, C.tools[Number(key) - 1].id); updateHUD(); }
    else if (key === 'g') { s.scanIndex = (s.scanIndex + 1) % C.scanTypes.length; updateHUD(); }
    else if (key === 'f') W.usePlant(s);
    else if (key === 'q') P.useKit(s);
    else if (key === 't') openPanel('serum-panel');
    else if (key === 'b') openPanel('build-panel');
    else if (key === 'x') SA.Buildings.recycle(s);
    else if (key === 'u') upgradeAtContext(s);
    else if (key === 'y') SA.Buildings.unlock(s);
    else if (key === 'p') saveWithFeedback(s);
  }
  function togglePause() { var s = app.state; if (s.mode !== 'playing' && s.mode !== 'paused') return; s.mode = s.mode === 'paused' ? 'playing' : 'paused'; el('pause').hidden = s.mode !== 'paused'; SA.Input.clear(); }
  function panelOpen() { return !!document.querySelector('.modal:not([hidden])'); }
  function openPanel(id) { closePanels(); el(id).hidden = false; app.pausedByPanel = app.state.mode === 'playing'; if (app.pausedByPanel) app.state.mode = 'paused'; SA.Input.clear(); updatePanels(); }
  function closePanels() { document.querySelectorAll('.modal').forEach(function (x) { x.hidden = true; }); if (app.pausedByPanel && app.state.mode === 'paused') app.state.mode = 'playing'; app.pausedByPanel = false; }
  function buildRangeText(def) { if (!def.range) return '此建筑不提供范围效果。'; return (def === C.buildings.turret ? '攻击范围' : '作用范围') + '：' + def.range + 'm。建造预览中的虚线圆环会同步显示该范围。'; }
  function updateBuildConfirm() { var pending = app.pendingBuild, def = pending && C.buildings[pending.buildingId], warning; if (!def) return; warning = pending.warning || ''; el('build-confirm-copy').textContent = '确认在选定位置建造“' + def.label + '”？'; el('build-confirm-cost').textContent = '将消耗：' + R.costText(def.cost) + '。确认后才能落地，取消不会扣除资源。'; el('build-confirm-range').textContent = buildRangeText(def); el('build-confirm-warning').textContent = warning; el('build-confirm-warning').hidden = !warning; }
  function requestBuild(s, point) { var placement = SA.Buildings.validatePlacement(s, point), def = placement.def; if (!placement.valid) return W.notice(s, '建造位置无效：' + placement.reason); if (!R.has(s.inventory, def.cost)) return W.notice(s, '资源不足：' + R.costText(def.cost)); app.pendingBuild = { x: point.x, y: point.y, buildingId: s.buildSelection, warning: placement.warning || '' }; openPanel('build-confirm-panel'); updateBuildConfirm(); }
  function cancelBuild() { app.pendingBuild = null; closePanels(); }
  function confirmBuild() { var pending = app.pendingBuild, s = app.state, before; if (!pending) return; s.buildSelection = pending.buildingId; before = s.buildings.length; SA.Buildings.place(s, pending); app.pendingBuild = null; closePanels(); if (s.buildings.length > before && !SA.Save.save(s)) W.notice(s, '建造完成，但存档失败：请检查浏览器本地存储。'); updateHUD(); }
  function formatSaveTime(savedAt) { if (!savedAt) return '未知时间'; var date = new Date(savedAt); return isNaN(date.getTime()) ? '未知时间' : date.toLocaleString('zh-CN', { hour12: false }); }
  function saveSummary(info) { return info.occupied ? '第 ' + info.day + ' 天 · ' + (info.isNight ? '夜袭' : '白天') + ' · 建筑 ' + info.buildingCount + ' · ' + formatSaveTime(info.savedAt) : '未保存：此档位没有任何数据'; }
  function escapeHTML(value) { return String(value).replace(/[&<>'"]/g, function (character) { return { '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[character]; }); }
  function updateSaveSlots() {
    var canSave = app.state.mode === 'playing' || app.state.mode === 'paused';
    el('save-slot-list').innerHTML = SA.Save.listSlots().map(function (info) {
      var title = info.label, renameButton = info.slot === 0 ? '' : '<button class="slot-rename" data-rename-slot="' + info.slot + '" title="重命名此手动档位">改名</button>', saveButton = info.slot === 0 ? '' : '<button data-save-slot="' + info.slot + '"' + (canSave ? '' : ' disabled') + '>' + (info.occupied ? '覆盖当前进度' : '保存当前进度') + '</button>';
      return '<section class="save-slot"><div><div class="save-slot-title"><b>' + escapeHTML(title) + '</b>' + renameButton + '</div><small>' + saveSummary(info) + '</small></div>' + saveButton + '<button data-load-slot="' + info.slot + '"' + (info.occupied ? '' : ' disabled') + '>读取</button></section>';
    }).join('');
  }
  function openSaveManager() { openPanel('save-panel'); updateSaveSlots(); }
  function openSaveRename(slot) { var info = SA.Save.slotInfo(slot); if (!info) return; app.pendingSaveRename = slot; openPanel('save-rename-panel'); el('save-rename-input').value = info.label; el('save-rename-input').select(); el('save-rename-input').focus(); }
  function cancelSaveRename() { app.pendingSaveRename = null; openSaveManager(); }
  function confirmSaveRename() { var slot = app.pendingSaveRename, name = el('save-rename-input').value; if (!SA.Save.renameSlot(slot, name)) return W.notice(app.state, '改名失败：浏览器存储不可用。'); app.pendingSaveRename = null; W.notice(app.state, '手动档位已命名为“' + SA.Save.slotName(slot) + '”。'); openSaveManager(); updateHUD(); }
  function saveManualSlot(slot) { var info = SA.Save.slotInfo(slot); if (info && info.occupied && !window.confirm('覆盖“' + info.label + '”吗？')) return; if (!SA.Save.saveSlot(app.state, slot)) return W.notice(app.state, '保存失败：浏览器存储不可用或空间不足。'); W.notice(app.state, '已保存至“' + info.label + '”：建筑 ' + app.state.buildings.length + '。'); updateSaveSlots(); updateHUD(); }
  function loadSavedSlot(slot) { var info = slot === 0 ? SA.Save.autoInfo() : SA.Save.slotInfo(slot), label = info ? info.label : ''; if (!info || !info.occupied) return W.notice(app.state, '该档位为空。'); if (app.state.mode !== 'title' && !window.confirm('读取“' + label + '”会放弃本次未保存的改动，继续吗？')) return; var s = slot === 0 ? SA.Save.load() : SA.Save.loadSlot(slot); if (!applyLoadedState(s, '已读取 ' + label + '：建筑 ' + (s ? s.buildings.length : 0) + '。')) W.notice(app.state, '读档失败：档案损坏或版本不兼容。'); }
  function upgradeAtContext(s) { if (R.distance(s.player, s.base) <= C.scanner.upgradeRange) W.upgradeScanner(s); else SA.Buildings.upgrade(s); }
  function updateManual() { if (!G || !G.pages.length) return; app.guidePage = R.clamp(app.guidePage, 0, G.pages.length - 1); el('manual-content').innerHTML = G.render(app.guidePage); el('manual-content').scrollTop = 0; el('guide-page').textContent = G.pages[app.guidePage].label + ' · ' + (app.guidePage + 1) + ' / ' + G.pages.length; el('guide-prev').disabled = app.guidePage === 0; el('guide-next').disabled = app.guidePage === G.pages.length - 1; }
  function openManual() { app.guidePage = 0; openPanel('manual-panel'); updateManual(); }
  function changeManualPage(delta) { app.guidePage += delta; updateManual(); }
  function saveWithFeedback(s) { var ok = SA.Save.save(s); W.notice(s, ok ? '进度已保存。' : '保存失败：浏览器存储不可用或空间不足。'); return ok; }
  function step(dt) {
    var s = app.state; if (s.mode !== 'playing') return;
    s.time += dt; s.notices.forEach(function (n) { n.time -= dt; }); s.notices = s.notices.filter(function (n) { return n.time > 0; });
    if (!s.forcedNight) { s.phaseTime += dt; var duration = s.isNight ? C.world.night : C.world.day; if (s.phaseTime >= duration) { s.phaseTime -= duration; s.isNight = !s.isNight; if (s.isNight) SA.Combat.spawn(s, Math.min(C.runtime.normalNightWaveCap, C.runtime.normalNightWaveBase + s.day * C.runtime.normalNightWavePerDay)); else { s.day += 1; W.dailySupply(s); SA.Save.save(s); } } }
    var held = SA.Input.state.held, dx = (held.d || held.arrowright ? 1 : 0) - (held.a || held.arrowleft ? 1 : 0), dy = (held.s || held.arrowdown ? 1 : 0) - (held.w || held.arrowup ? 1 : 0), sprint = !!held.shift;
    if (s.player.alive) { var zone = R.zoneAt(s.player.x, s.player.y), speed = C.player.speed * R.zoneSpeed(s, zone) * R.weightSpeed(s.inventory) * (sprint ? C.player.sprint : 1); if (dx || dy) { var length = Math.hypot(dx, dy); s.player.x = R.clamp(s.player.x + dx / length * speed * dt, 15, C.world.width - 15); s.player.y = R.clamp(s.player.y + dy / length * speed * dt, 15, C.world.height - 15); } if (!W.refillOxygen(s)) s.player.oxygen -= C.player.baseDrain * R.zoneOxygen(s, zone) * R.weightOxygen(s.inventory) * (sprint ? C.player.sprintOxygenMultiplier : 1) * dt; if (s.player.oxygen <= 0) { s.player.oxygen = 0; R.die(s); } s.player.invulnerable = Math.max(0, s.player.invulnerable - dt); W.collectNearby(s); W.refreshScan(s); } else { s.player.respawn -= dt; if (s.player.respawn <= 0) R.respawn(s); }
    handleMouse(s); SA.Buildings.tick(s, dt); SA.Combat.tick(s, dt); if (s.mode !== 'defeat') P.tick(s, dt); if (s.mode === 'playing' && s.signal.extractionActive && s.enemies.length < C.signal.evacuationEnemyThreshold && s.signal.evacuationSpawnCooldown <= 0) { SA.Combat.spawn(s, C.signal.evacuationSpawnCount); s.signal.evacuationSpawnCooldown = C.signal.evacuationSpawnCooldown; } if (s.mode === 'victory' || s.mode === 'defeat') finish(s.mode); SA.Input.finishStep();
  }
  function handleMouse(s) { if (!s.player.alive) return; var m = SA.Input.state.mouse, point = app.renderer.worldPoint(m); if (s.tool === 'weapon' && m.down && (!s.lastShot || s.time - s.lastShot >= C.runtime.shotCooldown)) { SA.Combat.shoot(s, point); s.lastShot = s.time; } else if (m.pressed) { if (s.tool === 'harvester') W.harvest(s, point); else if (s.tool === 'scanner') W.scan(s); else if (s.tool === 'build') requestBuild(s, point); else if (s.tool === 'repair') SA.Buildings.repair(s, point); } }
  function finish(mode) { el('end-screen').hidden = false; el('end-title').textContent = mode === 'victory' ? '撤离成功' : '基地失守'; el('end-copy').textContent = mode === 'victory' ? '救援艇已穿过风暴。未领取缓存仍保留在本局记录中。' : '可以从新游戏重新建立防线。'; SA.Save.save(app.state); }
  function frame(t) { if (!app.last) app.last = t; app.accumulator = Math.min(C.runtime.maxFrameDelta, app.accumulator + (t - app.last) / 1000); app.last = t; while (app.accumulator >= C.step) { step(C.step); app.accumulator -= C.step; } if (app.state.mode !== 'title') { app.renderer.draw(app.state); updateHUD(); } requestAnimationFrame(frame); }
  function directionTo(s, target) { var dx = target.x - s.player.x, dy = target.y - s.player.y, angle = Math.atan2(dy, dx) * 180 / Math.PI, directions = ['北', '东北', '东', '东南', '南', '西南', '西', '西北']; return directions[Math.round(angle / 45 + 8) % 8]; }
  function scanStatus(s) { var target = W.scanTarget(s), nextLabel = W.scanLabel(C.scanTypes[s.scanIndex]), typeLabel = s.scanType ? W.scanLabel(s.scanType) : '', scanner = '扫描器 Lv' + s.scannerLevel + ' · 范围 ' + W.scanRange(s) + 'm'; if (!s.scanActive) return scanner + ' · 导航关闭 · G 选择下一次扫描类别：' + nextLabel; if (!W.navigationVisible(s)) return scanner + ' · 导航待命：切至 2 采集器或 3 扫描器显示目标 · G 选择下一次扫描类别：' + nextLabel; if (!target) return scanner + ' · 导航持续搜索 ' + typeLabel + ' · 当前范围暂无目标，移动后自动续扫 · G 选择下一次扫描类别：' + nextLabel; return scanner + ' · 导航持续搜索 ' + typeLabel + ' · 锁定 ' + (target.type ? W.scanLabel(target.type) : typeLabel) + ' · ' + directionTo(s, target) + ' ' + Math.round(R.distance(s.player, target)) + 'm' + (target.underground ? ' · 地下 DIG' : '') + ' · G 选择下一次扫描类别：' + nextLabel; }
  function upgradeStatus(s) { var b = SA.Buildings.nearestTurret(s, s.player, C.runtime.turretUpgradeRange), turretCost = C.turretUpgrade.cost, scanner = C.scanner, scannerCost = scanner.upgradeCost; if (R.distance(s.player, s.base) <= scanner.upgradeRange) { if (s.scannerLevel >= scanner.maxLevel) return '扫描器升级：Lv' + s.scannerLevel + ' · 已满级 · 范围 ' + W.scanRange(s) + 'm'; return '扫描器升级：Lv' + s.scannerLevel + ' · 范围 ' + W.scanRange(s) + 'm · 成本 ' + R.costText(scannerCost) + ' · 按 U 升级'; } if (!b || b.type !== 'turret') return '升级：靠近炮塔 ' + C.runtime.turretUpgradeRange + 'm 按 U 升级；回到基地核心 ' + scanner.upgradeRange + 'm 内可升级扫描器。'; if (b.level >= C.turretUpgrade.max) return '炮塔升级：Lv' + b.level + ' · 已满级'; return '炮塔升级：Lv' + b.level + ' · 成本 ' + R.costText(turretCost) + ' · ' + (R.has(s.inventory, turretCost) ? 'ready' : '缺少 ' + Object.keys(turretCost).filter(function (k) { return (s.inventory[k] || 0) < turretCost[k]; }).map(function (k) { return C.resources[k].label + ' ' + (turretCost[k] - (s.inventory[k] || 0)); }).join(' / ')); }
  function contextStatus(s) {
    var closest = SA.Buildings.nearest(s, s.player, Infinity), def, distance;
    if (!closest) return '回收：暂无可回收结构。';
    def = C.buildings[closest.type]; distance = Math.round(R.distance(s.player, closest));
    if (s.tool === 'repair') return '维修：最近' + def.label + '距离 ' + distance + 'm（需 ≤' + C.runtime.repairRange + 'm）；鼠标点中结构 ≤' + C.runtime.repairTargetRange + 'm 后左键维修。';
    return '回收：最近' + def.label + '距离 ' + distance + 'm（需 ≤' + C.runtime.recycleRange + 'm）· ' + (distance <= C.runtime.recycleRange ? '按 X 回收' : '靠近后按 X 回收') + '。';
  }
  function signalStatus(s) { var hasBeacon = s.buildings.some(function (b) { return b.type === 'signal_beacon' && b.hp > 0; }); if (!hasBeacon) return '信号 ' + s.signal.progress + '% · 未建立信号台'; if (s.signal.extractionActive) return '信号 100% · 撤离坚守 ' + P.format(s.signal.extractionRemaining); if (s.signal.progress >= 100) return '信号 100% · 等待撤离状态同步'; return '信号 ' + s.signal.progress + '% · ' + (s.inventory.energy >= C.signal.energy ? '信号台在线：每 12 秒消耗 1 能量' : '信号台断能：需要 1 能量'); }
  function updateHUD() { var s = app.state, zone = R.zoneAt(s.player.x, s.player.y), zd = C.zones[zone], load = R.weight(s.inventory); setText('o2-value', Math.ceil(s.player.oxygen) + ' / ' + C.player.oxygen); setStyle('o2-fill', 'width', (100 * s.player.oxygen / C.player.oxygen) + '%'); setText('hp-value', Math.ceil(s.player.hp) + ' / ' + C.player.hp); setText('base-value', Math.ceil(s.base.hp) + ' / ' + C.base.hp + (s.base.shield ? ' + 护盾 ' + Math.ceil(s.base.shield) : '')); setText('zone', zd.label + ' | 氧耗 x' + R.zoneOxygen(s, zone).toFixed(2) + ' | 适应 Lv' + s.adaptations[zone] + (zd.recommend ? ' / 建议 Lv' + zd.recommend + '+' : '')); setText('cycle', s.signal.extractionActive ? '撤离坚守 ' + P.format(s.signal.extractionRemaining) : '第 ' + s.day + ' 天 · ' + (s.isNight ? '夜袭' : '白天') + ' ' + Math.ceil((s.isNight ? C.world.night : C.world.day) - s.phaseTime) + 's'); setText('signal', signalStatus(s)); setText('objective', P.objective(s)); setText('weight', '负重 ' + load.toFixed(1) + ' / ' + C.player.capacity + ' kg' + (load > C.player.capacity ? '（超重软惩罚）' : '')); setHTML('inventory', Object.keys(C.resources).map(function (k) { return '<span>' + C.resources[k].label + ' ' + s.inventory[k] + '</span>'; }).join('')); setHTML('notices', s.notices.map(function (n) { return '<li>' + escapeHTML(n.text) + '</li>'; }).join('')); setHTML('radio-log', (s.signal.log || []).slice().reverse().map(function (line) { return '<li>' + escapeHTML(line) + '</li>'; }).join('')); setText('scan', scanStatus(s)); setText('upgrade', upgradeStatus(s)); setText('context', contextStatus(s)); document.querySelectorAll('[data-tool]').forEach(function (b) { b.classList.toggle('active', b.dataset.tool === s.tool); }); }
  function setText(id, value) { if (app.hudCache[id] === value) return; app.hudCache[id] = value; el(id).textContent = value; }
  function setHTML(id, value) { if (app.hudCache[id] === value) return; app.hudCache[id] = value; el(id).innerHTML = value; }
  function setStyle(id, property, value) { var key = id + ':' + property; if (app.hudCache[key] === value) return; app.hudCache[key] = value; el(id).style[property] = value; }
  function updatePanels() { var s = app.state; el('build-list').innerHTML = C.buildOrder.map(function (id) { var d = C.buildings[id]; return '<button data-build="' + id + '"' + (!s.unlocked[id] ? ' class="locked"' : '') + '><b>' + d.label + '</b><small class="build-purpose">' + d.summary + '</small><small class="build-cost">' + R.costText(d.cost) + (s.unlocked[id] ? '' : ' · 未解锁') + '</small></button>'; }).join(''); el('serum-list').innerHTML = Object.keys(C.zones).map(function (z) { var level = s.adaptations[z], recipe = C.serumRecipes[z][level]; return '<button data-serum="' + z + '"><b>' + C.zones[z].label + ' Lv' + level + '</b><small>' + (recipe ? '下一等级：' + R.costText(recipe) : '已达 Lv4') + '</small></button>'; }).join(''); }
  function wire() { app.renderer = new SA.Renderer(el('game')); window.addEventListener('resize', function () { app.renderer.resize(); }); SA.Input.install(el('game'), dispatch); el('new-btn').onclick = function () { if (!SA.Save.exists() || confirm('开始新游戏会覆盖自动存档，手动档位会保留，继续吗？')) { SA.Save.remove(); start(); } }; el('continue-btn').onclick = continueGame; el('slots-btn').onclick = openSaveManager; el('delete-btn').onclick = function () { if (confirm('删除自动存档和全部手动档位？')) { SA.Save.removeAll(); showTitle(); } }; el('save-btn').onclick = openSaveManager; el('manual-btn').onclick = openManual; el('guide-prev').onclick = function () { changeManualPage(-1); }; el('guide-next').onclick = function () { changeManualPage(1); }; el('build-confirm-btn').onclick = confirmBuild; el('pause-btn').onclick = togglePause; el('resume-btn').onclick = togglePause; el('serum-btn').onclick = function () { openPanel('serum-panel'); }; el('build-btn').onclick = function () { openPanel('build-panel'); }; el('restart-btn').onclick = function () { SA.Save.remove(); start(); }; el('title-btn').onclick = showTitle; el('kit-btn').onclick = function () { P.useKit(app.state); }; el('craft-kit-btn').onclick = function () { P.craftKit(app.state); updatePanels(); }; document.addEventListener('click', function (e) { var b = e.target.closest('[data-tool],[data-build],[data-serum],[data-close],[data-save-slot],[data-load-slot]'); if (!b) return; if (b.dataset.tool) W.selectTool(app.state, b.dataset.tool); if (b.dataset.build) { app.state.buildSelection = b.dataset.build; W.selectTool(app.state, 'build'); closePanels(); } if (b.dataset.serum) { P.craftSerum(app.state, b.dataset.serum); updatePanels(); } if (b.dataset.saveSlot) saveManualSlot(Number(b.dataset.saveSlot)); if (b.dataset.loadSlot !== undefined) loadSavedSlot(Number(b.dataset.loadSlot)); if (b.dataset.close !== undefined) { if (b.closest('#pause')) togglePause(); else if (b.closest('#build-confirm-panel')) cancelBuild(); else closePanels(); } updateHUD(); }); document.addEventListener('visibilitychange', function () { if (document.hidden && app.state.mode === 'playing') SA.Save.save(app.state); }); showTitle(); requestAnimationFrame(frame); }
  window.__STAR_ABYSS_TEST__ = { startNewGame: function (seed) { start(seed); return snapshot(); }, snapshot: snapshot, advance: function (seconds) { var count = Math.min(C.runtime.maxTestSteps, Math.ceil(seconds / C.step)); for (var i = 0; i < count; i += 1) step(C.step); return snapshot(); }, setState: function (patch) { applyPatch(app.state, patch || {}); updateHUD(); return snapshot(); }, save: function () { return SA.Save.save(app.state); }, load: function () { continueGame(); return snapshot(); } };
  function snapshot() { var s = app.state; return JSON.parse(JSON.stringify({ mode: s.mode, day: s.day, isNight: s.isNight, player: s.player, base: s.base, inventory: s.inventory, adaptations: s.adaptations, unlocked: s.unlocked, buildings: s.buildings, enemies: s.enemies, signal: s.signal, deathDrop: s.deathDrop, tool: s.tool, buildSelection: s.buildSelection, scannerLevel: s.scannerLevel })); }
  function applyPatch(target, patch) { Object.keys(patch).forEach(function (k) { if (patch[k] && typeof patch[k] === 'object' && !Array.isArray(patch[k]) && target[k] && typeof target[k] === 'object' && !Array.isArray(target[k])) applyPatch(target[k], patch[k]); else if (Object.prototype.hasOwnProperty.call(target, k)) target[k] = JSON.parse(JSON.stringify(patch[k])); }); }
  document.addEventListener('DOMContentLoaded', wire);
  document.addEventListener('DOMContentLoaded', function () {
    el('save-rename-confirm').onclick = confirmSaveRename;
    el('save-rename-close').onclick = cancelSaveRename;
    el('save-rename-cancel').onclick = cancelSaveRename;
    el('save-rename-input').addEventListener('keydown', function (event) { if (event.key === 'Enter') confirmSaveRename(); });
    el('save-slot-list').addEventListener('click', function (event) { var button = event.target.closest('[data-rename-slot]'); if (button) openSaveRename(Number(button.dataset.renameSlot)); });
  });
  window.addEventListener('pagehide', function () { if (SA.app && SA.app.state && SA.app.state.mode !== 'title') SA.Save.save(SA.app.state); });
}(window.StarAbyss = window.StarAbyss || {}));
