import {MEDICINES} from './camp-data.mjs';
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function createCampUI({host=document.querySelector('#app'),onAction=()=>{},onOpenChange=()=>{},onUse=()=>{}}={}){
  const root=document.createElement('section');root.className='camp-foundation';root.hidden=true;
  const style=document.createElement('style');style.textContent=`
  .camp-foundation{position:absolute;inset:0;pointer-events:none;z-index:45;color:#eaf5f3;font:14px/1.5 system-ui,sans-serif}.camp-foundation[hidden],.camp-foundation [hidden]{display:none!important}
  .camp-foundation button{pointer-events:auto;min-height:44px;padding:9px 13px;border:1px solid #699a98;background:#192c33;color:#f4ffff;border-radius:5px;white-space:normal;text-align:left;font:inherit;cursor:pointer}.camp-foundation button:disabled{opacity:.45;cursor:default}.camp-foundation button:focus-visible{outline:2px solid #a1fff0;outline-offset:2px}
  .camp-prompt{position:absolute;right:22px;bottom:185px;max-width:min(290px,45vw);display:grid;gap:5px}.camp-status{background:#10202cdd;padding:6px 10px;border-radius:4px;margin:0}
  .camp-dialog{position:fixed;left:50%;top:50%;transform:translate(-50%,-50%);width:min(720px,calc(100vw - 32px));max-height:min(640px,calc(100vh - 36px));max-height:min(640px,calc(100dvh - 36px));pointer-events:auto;background:#0d1726f5;border:1px solid #73a8a3;border-radius:10px;box-shadow:0 18px 70px #000b;display:flex;flex-direction:column;overflow:hidden;font:15px/1.65 "Microsoft YaHei","PingFang SC",system-ui,sans-serif}.camp-dialog header{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px 16px;border-bottom:1px solid #345253;flex:none}.camp-dialog h2,.camp-dialog p{margin:0}.camp-body{min-height:0;overflow-y:auto;padding:14px 18px;overscroll-behavior:contain;scrollbar-width:thin}.camp-intro{display:flex;align-items:center;gap:15px;margin-bottom:12px}.camp-intro img{width:70px;height:95px;object-fit:cover;object-position:50% 18%;border-radius:5px}.camp-intro div{flex:1;min-width:0}.camp-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(230px,100%),1fr));gap:10px}.camp-card{border:1px solid #385357;border-radius:6px;padding:11px;display:grid;gap:8px;min-width:0}.camp-card h3{margin:0;font-size:15px}.camp-card small{color:#b9ccce}.camp-actions{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.camp-error{color:#ffc4ad;min-height:21px}.camp-tabs{display:flex;flex-wrap:wrap;gap:6px;margin-bottom:12px}.camp-tabs button[aria-selected=true]{background:#285453}.camp-body h3{margin-top:8px}.camp-note{color:#b8cccc;font-size:12px}
  @media(max-width:700px){.camp-dialog{width:calc(100vw - 16px);max-height:calc(100vh - 16px);max-height:calc(100dvh - 16px);font-size:14px}.camp-dialog header{padding:8px 10px}.camp-dialog h2{font-size:16px}.camp-body{padding:10px}.camp-intro img{width:48px;height:66px}.camp-prompt{right:10px;bottom:185px}.camp-prompt button{font-size:12px}}
  `;document.head.append(style);host.append(root);let view=null,open=false,tab='talk',destroyed=false,lastSignature='';
  const send=camp=>onAction({type:'camp',camp});
  function setOpen(value){if(value&& !view?.near)return false;open=!!value;document.body.classList.toggle('camp-dialog-open',open);if(open)tab='talk';onOpenChange(open);render();if(open)root.querySelector('[data-close]')?.focus();return true;}
  function button(text,action,params={},disabled=false){return `<button data-command="${action}" ${Object.entries(params).map(([k,v])=>`data-${k}="${escape(v)}"`).join(' ')} ${disabled||view.busy?'disabled':''}>${escape(text)}</button>`;}
  function content(){
    if(tab==='talk')return `<div class="camp-intro"><img src="assets/foundation/su-he-reference-v1.png" alt="苏禾"><div><p>这管血样里的结构会主动聚集能量。先学会处理伤口、补充电容与体力，再讨论强化。</p><p class="camp-note">三种医剂共用 45 秒恢复冷却。使用前可取消，生效后消耗一份。</p></div></div><div class="camp-actions">${!view.taught?button('交付 1 份掠兽血 · 接受教学','teach',{},view.sampleCount<1):'<span>基础医剂教学已解锁</span>'}${view.kitPending?button('领取一次性教学材料与 2 碎灵石','kit'):''}</div><p class="camp-note">血样来自实际击败的掠兽。首次教学材料只发放一次；第一炉免服务费，其后每炉 1 碎灵石。可出售已采集物资补充材料。</p>`;
    if(tab==='craft')return `<div class="camp-grid">${view.recipes.map(r=>`<article class="camp-card"><h3>${r.name} · T0 ${r.quality?'Q'+r.quality:'待备料'}</h3><p>${r.effect}</p><small>${r.ingredients.map(i=>`${i.name} ${i.owned}/${i.needed}`).join(' · ')}</small><small>制作 ${r.craftSeconds} 秒 · 服务费 ${r.fee} 碎灵石 · 无随机失败</small>${button('确认材料与服务费 · 开始制作','craft',{recipe:r.id},!r.canCraft)}</article>`).join('')}</div><h3>医师订单栏</h3><div class="camp-grid">${view.orders.map(o=>`<article class="camp-card"><strong>${o.name} · Q${o.quality}</strong><span>${o.remaining>0?'制作中 · '+Math.ceil(o.remaining)+' 秒':'制作完成'}</span>${button('领取成品','claim',{orderid:o.id},o.remaining>0)}</article>`).join('')||'<p>暂无订单。关闭窗口不丢失制作进度，背包满时成品保留。</p>'}</div>`;
    if(tab==='supplies')return `<p>随身碎灵石：${view.coins} · 医师剩余收购额度：${view.buybackBudget}</p><p class="camp-note">本营地首批研究补给为有限库存；不通过开关窗口刷新货物。</p><div class="camp-grid">${view.shop.map(o=>`<article class="camp-card"><strong>${o.name}</strong><span>库存 ${o.stock} · 每份 ${o.price} 碎灵石</span>${button('购买 1 份','buy',{item:o.id},o.stock<1||view.coins<o.price)}</article>`).join('')}${view.buyback.map(o=>`<article class="camp-card"><strong>出售 ${o.name}</strong><span>随身 ${o.owned} · 收购 ${o.price} 碎灵石</span>${button('确认出售 1 份','sell',{item:o.id},!o.owned||view.buybackBudget<o.price)}</article>`).join('')}</div>`;
    return `<p>共享恢复冷却：${Math.ceil(view.cooldown)} 秒</p><div class="camp-grid">${view.medicines.map(m=>`<article class="camp-card"><h3>${m.name} × ${m.quantity} · T${m.tier} Q${m.quality}</h3><p>${m.effect}</p><small>使用 ${m.useSeconds} 秒；用药中只能慢走。</small>${button('关闭对话并使用','use-start',{itemid:m.id},view.canUseAfterClose===false||view.cooldown>0||!!view.use||m.status!=='normal')}</article>`).join('')||'<p>背包中暂无医剂。</p>'}</div>`;
  }
  function render(){if(destroyed||!view)return;const scroll=root.querySelector('.camp-body')?.scrollTop||0;const focused=root.contains(document.activeElement)?Object.fromEntries(Object.entries(document.activeElement.dataset)):null;
    root.hidden=false;root.innerHTML=`<div class="camp-prompt" ${open?'hidden':''}>${view.near?'<button data-open>苏禾 · 生物医师 · F</button>':''}${view.use?`<p class="camp-status">${MEDICINES[view.use.recipe].name} · ${view.use.remaining.toFixed(1)} 秒</p>${button('取消使用','use-cancel')}`:''}</div><section class="camp-dialog" role="dialog" aria-modal="false" aria-label="苏禾医务服务" ${open?'':'hidden'}><header><h2>苏禾 <small>生物医师</small></h2><button data-close>离开 · Esc</button></header><div class="camp-body"><nav class="camp-tabs">${[['talk','交谈'],['craft','医剂炼制'],['supplies','研究补给'],['medicine','随身医剂']].map(([id,label])=>`<button data-tab="${id}" aria-selected="${tab===id}">${label}</button>`).join('')}</nav>${content()}<p class="camp-error" role="status">${escape(view.error||'')}</p></div></section>`;
    const body=root.querySelector('.camp-body');if(body)body.scrollTop=scroll;if(focused&&Object.keys(focused).length)[...root.querySelectorAll('button')].find(b=>Object.entries(focused).every(([k,v])=>b.dataset[k]===v))?.focus({preventScroll:true});
  }
  root.addEventListener('click',event=>{const b=event.target.closest('button');if(!b||b.disabled)return;if(b.hasAttribute('data-open'))return setOpen(true);if(b.hasAttribute('data-close'))return setOpen(false);if(b.dataset.tab){tab=b.dataset.tab;return render();}if(b.dataset.command){const action=b.dataset.command;if(action==='use-start'){setOpen(false);onUse();}send({action,recipe:b.dataset.recipe,orderId:b.dataset.orderid,item:b.dataset.item,itemId:b.dataset.itemid});}});
  return {update(next){view=next;if(open&&!next.near){setOpen(false);return;}const signature=JSON.stringify({...next,cooldown:Math.ceil(next.cooldown),orders:next.orders.map(o=>({...o,remaining:Math.ceil(o.remaining)})),use:next.use?{...next.use,remaining:Math.ceil(next.use.remaining*10)/10}:null});if(signature!==lastSignature){lastSignature=signature;render();}else root.hidden=false;},open:()=>setOpen(true),close:()=>setOpen(false),get isOpen(){return open;},hide(){root.hidden=true;if(open)setOpen(false);root.hidden=true;},destroy(){destroyed=true;document.body.classList.remove('camp-dialog-open');root.remove();style.remove();}};
}
