'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const root = path.resolve(__dirname, '..', 'js');
const context = { window: {}, console, localStorage: (() => { const data = new Map(); return { setItem(k,v){data.set(k,String(v));}, getItem(k){return data.has(k)?data.get(k):null;}, removeItem(k){data.delete(k);} }; })() };
context.window = context; vm.createContext(context);
['config.js','state.js','rules.js','world.js','buildings.js','combat.js','progression.js','save.js','guide.js'].forEach(f => vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'), context, { filename:f }));
const SA = context.StarAbyss;
function state(){ const s=SA.State.create(42); s.mode='playing'; return s; }
test('重量和区域压力使用软惩罚并封顶', () => { const s=state(); Object.keys(s.inventory).forEach(k=>s.inventory[k]=0); s.inventory.iron=100; assert.equal(SA.Rules.weight(s.inventory),50); assert.equal(SA.Rules.weightSpeed(s.inventory),0.5); assert.equal(SA.Rules.weightOxygen(s.inventory),1.5); assert.equal(SA.Rules.zoneOxygen(s,'gravity'),4); s.adaptations.gravity=2; assert.ok(SA.Rules.zoneOxygen(s,'gravity')<3); assert.equal(SA.Rules.zoneSpeed(s,'gravity'),1); });
test('原子消费失败不会部分扣除', () => { const inv={iron:10,energy:0}; assert.equal(SA.Rules.consume(inv,{iron:5,energy:1}),false); assert.deepEqual(inv,{iron:10,energy:0}); });
test('死亡掉落合并且复活可继续行动', () => { const s=state(); s.day=2; s.inventory.iron=9; SA.Rules.die(s); assert.equal(s.inventory.iron,5); assert.equal(s.deathDrop.items.iron,4); s.player.alive=true; s.inventory.iron=4; SA.Rules.die(s); assert.equal(s.deathDrop.items.iron,6); SA.Rules.respawn(s); assert.equal(s.player.oxygen,90); assert.ok(s.player.invulnerable>0); });
test('非战斗撞击死亡不发奖励', () => { const s=state(); const e={hp:1,rewarded:false}; SA.Combat.kill(s,e,'impact'); assert.equal(s.inventory.iron,0); assert.equal(s.kills,0); const e2={hp:1,rewarded:false}; SA.Combat.kill(s,e2,'turret'); assert.equal(s.inventory.iron,2); assert.equal(s.kills,1); });
test('武器投射物击杀敌人会给奖励并标明击杀来源', () => { const s=state(), enemy={id:'target',x:s.player.x+80,y:s.player.y,hp:14,maxHp:14,speed:0,radius:13,attack:0,variant:0,rewarded:false}; s.enemies=[enemy]; SA.Combat.shoot(s,{x:enemy.x,y:enemy.y}); SA.Combat.tick(s,.2); assert.equal(s.enemies.length,0); assert.equal(s.inventory.iron,2); assert.equal(s.inventory.biomass,1); assert.match(s.notices[0].text,/武器击杀/); });
test('敌人抵达基地后持续攻击而非自动消失', () => { const s=state(), enemy={id:'raider',x:s.base.x+10,y:s.base.y,hp:100,maxHp:100,speed:0,radius:13,attack:0,variant:0,rewarded:false}; s.player.x=s.base.x+500; s.player.y=s.base.y+500; s.enemies=[enemy]; const before=s.base.hp; SA.Combat.tick(s,.01); assert.equal(s.enemies.length,1); assert.equal(s.base.hp,before-SA.Config.enemy.contactBase); assert.match(s.notices[0].text,/正在攻击基地/); });
test('扫描会话在当前安全区域按距离锁定、跨工具保留，并在采空后按会话类别接续', () => {
  const s=state();
  s.nodes=[{id:'visible',type:'iron',x:s.player.x+10,y:s.player.y,amount:1,underground:false,revealed:true},{id:'underground',type:'iron',x:s.player.x+20,y:s.player.y,amount:1,underground:true,revealed:false},{id:'next',type:'iron',x:s.player.x+30,y:s.player.y,amount:1,underground:false,revealed:true}];
  SA.World.selectTool(s,'scanner'); SA.World.scan(s);
  assert.equal(s.scanActive,true); assert.equal(s.scanType,'iron'); assert.equal(s.scanTarget,'visible'); assert.equal(s.nodes[1].revealed,false);
  ['harvester','weapon','build','repair'].forEach(tool=>{ SA.World.selectTool(s,tool); assert.equal(s.scanTarget,'visible'); assert.equal(s.scanActive,true); });
  SA.World.selectTool(s,'harvester'); SA.World.harvest(s,{x:s.player.x+30,y:s.player.y});
  assert.equal(s.scanTarget,'visible');
  SA.World.harvest(s,{x:s.player.x+10,y:s.player.y}); assert.equal(s.scanTarget,'underground'); assert.equal(s.nodes.find(n=>n.id==='underground').revealed,true);
});
test('扫描保留当前区域资源，仍不导向其他未适应区域', () => {
  const s=state();
  s.nodes=[{id:'near_crash',type:'iron',x:s.base.x+120,y:s.base.y,amount:1,underground:false,revealed:true},{id:'cold',type:'iron',x:s.base.x,y:s.base.y-600,amount:1,underground:true,revealed:false}];
  SA.World.scan(s); assert.equal(s.scanTarget,'near_crash'); assert.equal(SA.World.scanZone(s,s.nodes[0]),'crash'); assert.equal(SA.World.zoneIsNavigable(s,'cold'),false);
  s.nodes=[s.nodes[1]]; s.player.x=s.base.x; s.player.y=s.base.y-400; SA.World.scan(s); assert.equal(s.scanTarget,null); assert.match(s.notices[0].text,/未适应区域/);
  s.player.x=s.base.x; s.player.y=s.base.y-550; assert.equal(SA.World.zoneIsNavigable(s,'cold'),true); SA.World.scan(s); assert.equal(s.scanTarget,'cold'); assert.equal(s.nodes[0].revealed,true);
});
test('扫描器有范围限制且可在基地升级扩大范围', () => { const s=state(), scanner=SA.Config.scanner; s.player.x=s.base.x; s.player.y=s.base.y; s.nodes=[{id:'far_iron',type:'iron',x:s.player.x+scanner.baseRange+1,y:s.player.y,amount:1,underground:false,revealed:true}]; SA.World.scan(s); assert.equal(s.scanTarget,null); assert.match(s.notices[0].text,/范围外/); Object.keys(s.inventory).forEach(k=>s.inventory[k]=100); SA.World.upgradeScanner(s); assert.equal(s.scannerLevel,1); assert.equal(SA.World.scanRange(s),scanner.baseRange+scanner.rangePerLevel); SA.World.scan(s); assert.equal(s.scanTarget,'far_iron'); });
test('扫描会话跨采集器持续搜索，移动进入范围后自动续锁', () => { const s=state(), target={id:'moving_target',type:'iron',x:s.player.x+500,y:s.player.y,amount:1,underground:false,revealed:true}; s.adaptations.heat=2; s.nodes=[target]; SA.World.scan(s); assert.equal(s.scanActive,true); assert.equal(s.scanTarget,null); SA.World.selectTool(s,'harvester'); s.player.x+=160; assert.equal(SA.World.refreshScan(s).id,'moving_target'); assert.equal(s.scanTarget,'moving_target'); target.amount=0; assert.equal(SA.World.refreshScan(s),null); assert.equal(s.scanTarget,null); });
test('扫描会话可跨工具保留，但仅在扫描器或采集器中显示导航画面', () => { const s=state(); s.scanActive=true; s.tool='scanner'; assert.equal(SA.World.navigationVisible(s),true); s.tool='harvester'; assert.equal(SA.World.navigationVisible(s),true); ['weapon','build','repair'].forEach(tool=>{ s.tool=tool; assert.equal(SA.World.navigationVisible(s),false); }); s.scanActive=false; s.tool='scanner'; assert.equal(SA.World.navigationVisible(s),false); });
test('G 与运行中的会话隔离，扫描器再次选择明确关闭且不会隐式复活', () => {
  const s=state(); s.nodes=[{id:'iron',type:'iron',x:s.player.x+20,y:s.player.y,amount:1,underground:false,revealed:true},{id:'bio',type:'biomass',x:s.player.x+30,y:s.player.y,amount:1,underground:false,revealed:true}];
  SA.World.selectTool(s,'scanner'); SA.World.scan(s); s.scanIndex=1;
  assert.equal(s.scanType,'iron'); assert.equal(SA.World.scanTarget(s).id,'iron');
  SA.World.selectTool(s,'scanner'); assert.equal(s.scanActive,false); assert.equal(s.scanType,null); assert.equal(s.scanTarget,null); assert.equal(s.notices[0].text,'扫描导航已关闭。');
  SA.World.selectTool(s,'harvester'); SA.World.harvest(s,{x:s.nodes[1].x,y:s.nodes[1].y}); assert.equal(s.scanActive,false); assert.equal(s.scanTarget,null);
});
test('无候选、失效植物和缓存只清除目标并保持会话', () => {
  const s=state(); s.scanIndex=6; SA.World.selectTool(s,'scanner'); SA.World.scan(s);
  assert.equal(s.scanActive,true); assert.equal(s.scanType,'cache'); assert.equal(s.scanTarget,null);
  s.plants=[{id:'plant',x:s.player.x+10,y:s.player.y,oxygen:3}]; s.scanIndex=4; SA.World.scan(s); s.player.oxygen=SA.Config.player.oxygen-3; SA.World.usePlant(s);
  assert.equal(s.scanActive,true); assert.equal(s.scanType,'oxygen_plant'); assert.equal(s.scanTarget,null);
  s.caches=[{id:'cache',x:s.player.x+10,y:s.player.y,rewards:{iron:1},collected:false}]; s.scanIndex=6; SA.World.scan(s); SA.World.collectNearby(s);
  assert.equal(s.scanActive,true); assert.equal(s.scanType,'cache'); assert.equal(s.scanTarget,null);
});
test('基地与氧气站范围会立即补满氧气', () => { const s=state(); s.player.oxygen=12; s.player.x=s.base.x; s.player.y=s.base.y; assert.equal(SA.World.oxygenRefillAvailable(s),true); assert.equal(SA.World.refillOxygen(s),true); assert.equal(s.player.oxygen,SA.Config.player.oxygen); s.player.x=s.base.x+320; s.player.y=s.base.y; s.player.oxygen=21; s.buildings=[{id:'o2',type:'o2_station',x:s.player.x,y:s.player.y,hp:100,maxHp:100,level:0,timer:0}]; assert.equal(SA.World.refillOxygen(s),true); assert.equal(s.player.oxygen,SA.Config.player.oxygen); s.buildings[0].hp=0; s.player.oxygen=21; assert.equal(SA.World.refillOxygen(s),false); assert.equal(s.player.oxygen,21); });
test('蓝图会话匹配复合资源并按蓝图类别接续', () => {
  const s=state(); s.scanIndex=5; s.nodes=[{id:'core',type:'energy_core',x:s.player.x+100,y:s.player.y,amount:1,underground:false,revealed:true},{id:'crystal',type:'void_crystal',x:s.player.x+90,y:s.player.y,amount:1,underground:false,revealed:true},{id:'iron',type:'iron',x:s.player.x+10,y:s.player.y,amount:1,underground:false,revealed:true}];
  SA.World.scan(s); assert.equal(s.scanType,'blueprint'); assert.equal(s.scanTarget,'crystal'); s.scanIndex=0; SA.World.harvest(s,{x:s.player.x+90,y:s.player.y}); assert.equal(s.scanTarget,'core');
});
test('存档兼容新旧扫描会话格式', () => {
  const s=state(); s.nodes=[{id:'keep',type:'iron',x:1,y:1,amount:1,underground:false,revealed:true}];
  s.scanActive=true; s.scanType='iron'; s.scanTarget='keep'; let loaded=SA.Save.sanitize(JSON.parse(JSON.stringify(s))); assert.equal(loaded.scanActive,true); assert.equal(loaded.scanType,'iron'); assert.equal(loaded.scanTarget,'keep');
  s.scanTarget='gone'; loaded=SA.Save.sanitize(JSON.parse(JSON.stringify(s))); assert.equal(loaded.scanActive,true); assert.equal(loaded.scanType,'iron'); assert.equal(loaded.scanTarget,null);
  const legacy=JSON.parse(JSON.stringify(s)); delete legacy.scanActive; delete legacy.scanType; legacy.scanTarget='keep'; loaded=SA.Save.sanitize(legacy); assert.equal(loaded.scanActive,true); assert.equal(loaded.scanType,'iron'); assert.equal(loaded.scanTarget,'keep');
  legacy.scanTarget='gone'; loaded=SA.Save.sanitize(legacy); assert.equal(loaded.scanActive,false); assert.equal(loaded.scanType,null); assert.equal(loaded.scanTarget,null);
  s.scanActive=false; s.scanType='iron'; s.scanTarget='keep'; loaded=SA.Save.sanitize(JSON.parse(JSON.stringify(s))); assert.equal(loaded.scanActive,false); assert.equal(loaded.scanType,null); assert.equal(loaded.scanTarget,null);
});
test('建造验证与放置共享规则且预览验证不扣资源', () => { const s=state(); s.buildSelection='turret'; s.inventory.iron=20; s.inventory.void_crystal=5; const point={x:s.player.x+100,y:s.player.y}, remoteCrash={x:s.base.x+300,y:s.base.y}, unadaptedHeat={x:s.base.x+650,y:s.base.y}; assert.equal(SA.Buildings.validatePlacement(s,point).valid,true); assert.equal(SA.Buildings.validatePlacement(s,remoteCrash).valid,true); assert.equal(SA.Buildings.validatePlacement(s,unadaptedHeat).valid,false); const before=JSON.stringify(s.inventory); assert.equal(SA.Buildings.validatePlacement(s,{x:s.base.x,y:s.base.y}).valid,false); assert.equal(JSON.stringify(s.inventory),before); SA.Buildings.place(s,point); assert.equal(s.buildings.length,1); });
test('熔岩区低热适应建造会预警并显示持续侵蚀', () => { const s=state(), point={x:s.base.x+650,y:s.base.y}; s.player.x=point.x; s.player.y=point.y; s.buildSelection='turret'; Object.keys(s.inventory).forEach(k=>s.inventory[k]=100); const placement=SA.Buildings.validatePlacement(s,point); assert.equal(placement.valid,true); assert.match(placement.warning,/熔岩侵蚀.*Lv0\/Lv2.*-0\.10/); SA.Buildings.place(s,point); const turret=s.buildings[0], hp=turret.hp; assert.match(s.notices[0].text,/熔岩侵蚀/); assert.equal(SA.Buildings.isHeatExposed(s,turret),true); SA.Buildings.tick(s,1); assert.equal(turret.hp,hp-SA.Config.runtime.buildingHeatDamage); s.adaptations.heat=2; assert.equal(SA.Buildings.heatWarning(s,point),''); assert.equal(SA.Buildings.isHeatExposed(s,turret),false); });
test('每种建筑都提供用于目录展示的用途说明', () => { SA.Config.buildOrder.forEach(id => { const d=SA.Config.buildings[id]; assert.equal(typeof d.summary,'string'); assert.ok(d.summary.length > 6); }); });
test('生存手册提供可翻页的完整页面并复用建筑和区域配置', () => { assert.equal(SA.Guide.pages.length,6); assert.equal(SA.Guide.pages.map(page => page.id).join(','),'overview,explore,zones,buildings,defense,controls'); const zones=SA.Guide.render(2), buildings=SA.Guide.render(3); Object.keys(SA.Config.zones).forEach(id => assert.match(zones,new RegExp(SA.Config.zones[id].label))); SA.Config.buildOrder.forEach(id => assert.match(buildings,new RegExp(SA.Config.buildings[id].label))); assert.equal(SA.Guide.render(99),''); });
test('炮台开火更新瞄准与闪光，已毁炮台不作用', () => { const s=state(); const turret={id:'t',type:'turret',x:s.player.x,y:s.player.y,hp:100,maxHp:100,level:0,timer:0,aimAngle:0,fireFlash:0}; s.buildings=[turret]; s.enemies=[{id:'e',x:turret.x,y:turret.y+50,hp:100,maxHp:100,speed:0,radius:13,attack:0,variant:0,rewarded:false}]; SA.Combat.tick(s,0.01); assert.equal(turret.aimAngle,Math.PI/2); assert.equal(turret.fireFlash,SA.Config.runtime.turretFireFlashDuration); const hp=s.enemies[0].hp; turret.hp=0; turret.timer=0; turret.fireFlash=0; SA.Combat.tick(s,0.01); assert.equal(s.enemies[0].hp,hp); assert.equal(turret.fireFlash,0); });
test('空闲炮塔计时不会降为负数，旧负计时存档也能恢复建筑', () => { const s=state(); s.buildings=[{id:'idle',type:'turret',x:s.player.x+100,y:s.player.y,hp:100,maxHp:100,level:0,timer:0,aimAngle:0,fireFlash:0}]; SA.Combat.tick(s,120); assert.equal(s.buildings[0].timer,0); const raw=JSON.parse(JSON.stringify(s)); raw.buildings[0].timer=-120; raw.savedAt=Date.now(); const loaded=SA.Save.sanitize(raw); assert.equal(loaded.buildings.length,1); assert.equal(loaded.buildings[0].id,'idle'); assert.equal(loaded.buildings[0].timer,0); assert.equal(loaded.savedAt,raw.savedAt); });

test('采集严格使用鼠标预选目标，不会点击空处拿最近资源', () => { const s=state(), first={id:'first',type:'biomass',x:s.player.x+70,y:s.player.y,amount:1,underground:false,revealed:true}, second={id:'second',type:'iron',x:s.player.x+92,y:s.player.y,amount:1,underground:false,revealed:true}; s.nodes=[first,second]; SA.World.harvest(s,{x:first.x,y:first.y}); assert.equal(s.inventory.biomass,1); assert.equal(s.inventory.iron,0); assert.equal(s.nodes.length,1); SA.World.harvest(s,{x:s.player.x-400,y:s.player.y}); assert.equal(s.inventory.iron,0); assert.match(s.notices[0].text,/点击/); });
test('采集和建造允许当前区域，跨入未适应区域会被拒绝', () => { const s=state(), local={id:'cold_local',type:'iron',x:s.base.x,y:s.base.y-600,amount:1,underground:false,revealed:true}, cross={id:'cold_cross',type:'iron',x:s.base.x,y:s.base.y-450,amount:1,underground:false,revealed:true}; s.player.x=s.base.x; s.player.y=s.base.y-550; s.nodes=[local]; s.buildSelection='turret'; assert.equal(SA.World.zoneIsNavigable(s,'cold'),true); assert.equal(SA.Buildings.validatePlacement(s,local).valid,true); SA.World.harvest(s,local); assert.equal(s.inventory.iron,1); s.player.y=s.base.y-400; s.nodes=[cross]; assert.equal(SA.Buildings.validatePlacement(s,cross).valid,false); SA.World.harvest(s,cross); assert.equal(s.inventory.iron,1); assert.match(s.notices[0].text,/未适应区域/); s.adaptations.cold=2; assert.equal(SA.Buildings.validatePlacement(s,cross).valid,true); SA.World.harvest(s,cross); assert.equal(s.inventory.iron,2); });
test('地图外资源不可采集、扫描或建造', () => { const s=state(), outside={id:'outside',type:'biomass',x:s.player.x,y:-10,amount:3,underground:false,revealed:true}; s.player.y=20; s.nodes=[outside]; s.scanIndex=1; SA.World.harvest(s,outside); assert.equal(s.inventory.biomass,0); assert.equal(outside.amount,3); SA.World.scan(s); assert.equal(s.scanTarget,null); assert.equal(SA.Buildings.validatePlacement(s,outside).valid,false); assert.match(SA.Buildings.validatePlacement(s,outside).reason,/地图边界/); });
test('初始资源与植株生成在地图安全边距内', () => { for (let seed=1; seed<=40; seed+=1) { const s=SA.State.create(seed); s.nodes.concat(s.plants).forEach(point => assert.equal(SA.Rules.pointInWorld(point,SA.Config.world.edgeMargin),true)); } });
test('读取存档会清理地图外对象', () => { const s=state(); s.nodes=[{id:'inside',type:'iron',x:10,y:10,amount:1,underground:false,revealed:true},{id:'outside',type:'iron',x:10,y:-1,amount:1,underground:false,revealed:true}]; s.plants=[{id:'outside_plant',x:SA.Config.world.width+1,y:10,oxygen:10}]; s.deathDrop={x:-1,y:10,items:{iron:2}}; const loaded=SA.Save.sanitize(JSON.parse(JSON.stringify(s))); assert.deepEqual(Array.from(loaded.nodes,n=>n.id),['inside']); assert.equal(loaded.plants.length,0); assert.equal(loaded.deathDrop,null); });
test('建筑建造、升级、维修、回收遵守成本', () => { const s=state(); Object.keys(s.inventory).forEach(k=>s.inventory[k]=100); s.buildSelection='turret'; SA.Buildings.place(s,{x:s.player.x+100,y:s.player.y}); assert.equal(s.buildings.length,1); const b=s.buildings[0]; b.hp=50; s.player.x=b.x; s.player.y=b.y; SA.Buildings.repair(s,b); assert.equal(b.hp,85); SA.Buildings.upgrade(s); assert.equal(b.level,1); const before=s.inventory.iron; SA.Buildings.recycle(s); assert.equal(s.buildings.length,0); assert.ok(s.inventory.iron>before); });
test('损毁建筑会移除并留下可持久查询的原因', () => { const s=state(); s.buildings=[{id:'lost',type:'turret',x:s.player.x+100,y:s.player.y,hp:0,maxHp:100,level:0,timer:0,aimAngle:0,fireFlash:0,lastDamageCause:'敌袭'}]; SA.Buildings.tick(s,0.1); assert.equal(s.buildings.length,0); assert.match(s.notices[0].text,/已损毁.*敌袭/); assert.match(s.signal.log[s.signal.log.length-1],/建筑损毁：炮塔（敌袭）/); });
test('炮塔升级在范围外、不足或满级时不扣资源，成功时原子扣除', () => { const s=state(), cost=SA.Config.turretUpgrade.cost, turret={id:'t',type:'turret',x:s.player.x+200,y:s.player.y,hp:100,maxHp:100,level:0,timer:0}; s.buildings=[turret]; Object.keys(s.inventory).forEach(k=>s.inventory[k]=100); const before=JSON.stringify(s.inventory); SA.Buildings.upgrade(s); assert.equal(JSON.stringify(s.inventory),before); assert.match(s.notices[0].text,/距离 200m.*成本：/); turret.x=s.player.x; Object.keys(s.inventory).forEach(k=>s.inventory[k]=0); const insufficient=JSON.stringify(s.inventory); SA.Buildings.upgrade(s); assert.equal(JSON.stringify(s.inventory),insufficient); assert.match(s.notices[0].text,/升级资源不足：.*缺少/); turret.level=SA.Config.turretUpgrade.max; Object.keys(s.inventory).forEach(k=>s.inventory[k]=100); const full=JSON.stringify(s.inventory); SA.Buildings.upgrade(s); assert.equal(JSON.stringify(s.inventory),full); assert.match(s.notices[0].text,/Lv3/); turret.level=0; const successBefore=JSON.parse(JSON.stringify(s.inventory)); SA.Buildings.upgrade(s); assert.equal(turret.level,1); Object.keys(cost).forEach(k=>assert.equal(s.inventory[k],successBefore[k]-cost[k])); assert.match(s.notices[0].text,/已消耗：/); });
test('信号周期、里程碑和撤离幂等', () => { const s=state(); s.inventory.energy=30; s.buildings.push({type:'signal_beacon',timer:0,hp:100,maxHp:100,x:s.base.x+100,y:s.base.y}); SA.Progression.tick(s,12); assert.equal(s.signal.progress,5); assert.equal(s.inventory.energy,29); assert.match(s.notices[0].text,/信号台广播/); SA.Progression.setProgress(s,100); assert.equal(s.caches.length,4); assert.equal(s.signal.extractionActive,true); assert.equal(s.mode,'playing'); SA.Progression.setProgress(s,100); assert.equal(s.caches.length,4); });
test('血清公式降低压力', () => { const s=state(); Object.keys(s.inventory).forEach(k=>s.inventory[k]=100); const before=SA.Rules.zoneOxygen(s,'cold'); SA.Progression.craftSerum(s,'cold'); assert.equal(s.adaptations.cold,1); assert.ok(SA.Rules.zoneOxygen(s,'cold')<before); });
test('存档往返、坏版本和撤离零秒边界', () => { const s=state(); s.inventory.iron=17; s.scannerLevel=1; s.buildings=[{id:'saved_turret',type:'turret',x:s.player.x+100,y:s.player.y,hp:100,maxHp:100,level:0,timer:0,aimAngle:0,fireFlash:0}]; s.signal.progress=100; s.signal.extractionActive=true; s.forcedNight=true; s.isNight=true; s.signal.extractionRemaining=0; assert.equal(SA.Save.save(s),true); const loaded=SA.Save.load(); assert.equal(loaded.inventory.iron,17); assert.equal(loaded.scannerLevel,1); assert.equal(loaded.buildings.length,1); assert.equal(loaded.buildings[0].id,'saved_turret'); assert.equal(loaded.signal.extractionRemaining,0.1); assert.equal(loaded.forcedNight,true); assert.equal(loaded.isNight,true); assert.equal(SA.Save.sanitize({schema:999}),null); assert.equal(SA.Save.sanitize(null),null); });
test('自动存档与三个手动档位相互独立，并显示建筑数量', () => { SA.Save.removeAll(); const auto=state(), first=state(), second=state(); auto.day=2; auto.buildings=[{id:'auto_t',type:'turret',x:auto.player.x+100,y:auto.player.y,hp:100,maxHp:100,level:0,timer:0,aimAngle:0,fireFlash:0}]; first.day=3; first.inventory.iron=9; second.day=4; second.inventory.biomass=7; assert.equal(SA.Save.save(auto),true); assert.equal(SA.Save.saveSlot(first,1),true); assert.equal(SA.Save.saveSlot(second,2),true); const slots=SA.Save.listSlots(); assert.equal(slots.length,4); assert.equal(slots[0].buildingCount,1); assert.equal(slots[1].day,3); assert.equal(slots[2].day,4); assert.equal(slots[3].occupied,false); assert.equal(SA.Save.load().buildings[0].id,'auto_t'); assert.equal(SA.Save.loadSlot(1).inventory.iron,9); assert.equal(SA.Save.loadSlot(2).inventory.biomass,7); SA.Save.removeAll(); });
test('手动档位名称独立持久化，覆盖存档和读取后保持不变', () => { SA.Save.removeAll(); const s=state(); assert.equal(SA.Save.slotInfo(1).label,'手动档位 1'); assert.equal(SA.Save.renameSlot(1,'熔岩区前哨'),true); assert.equal(SA.Save.slotInfo(1).label,'熔岩区前哨'); assert.equal(SA.Save.saveSlot(s,1),true); assert.equal(SA.Save.slotInfo(1).label,'熔岩区前哨'); assert.equal(SA.Save.loadSlot(1).day,s.day); assert.equal(SA.Save.renameSlot(1,'  <北线>   存档  '),true); assert.equal(SA.Save.slotInfo(1).label,'北线 存档'); assert.equal(SA.Save.renameSlot(1,''),true); assert.equal(SA.Save.slotInfo(1).label,'手动档位 1'); assert.equal(SA.Save.renameSlot(0,'无效'),false); SA.Save.removeAll(); assert.equal(SA.Save.slotInfo(1).label,'手动档位 1'); });
