"""Editable leg rigs on the existing image-derived characters. No remote generation."""
import bpy, math, json
from pathlib import Path
from mathutils import Vector
ROOT=Path(__file__).resolve().parents[4]
OUT=ROOT/'playable/assets/camp-v2/actors'
DOC=ROOT/'docs/art/camp-v2/actors'
OUT.mkdir(parents=True,exist_ok=True);DOC.mkdir(parents=True,exist_ok=True)
H=1.78; STRIDE=.32; DROP=.012
def clamp(v,a=0,b=1):return max(a,min(b,v))
def angles(p):
    p%=1
    if p<.5:z=STRIDE*.25-STRIDE*p;lift=0
    else:
        q=(p-.5)*2;z=-STRIDE*.25+STRIDE*.5*(q*q*(3-2*q));lift=.035*math.sin(math.pi*q)**2
    a=H*.23;b=H*.21;dy=a+b-DROP-lift;d=math.hypot(dy,z)
    knee=math.pi-math.acos(clamp((a*a+b*b-d*d)/(2*a*b),-1,1))
    thigh=math.atan2(-z,dy)-math.acos(clamp((a*a+d*d-b*b)/(2*a*d),-1,1))
    return [thigh,knee,-thigh-knee]
frames=[angles(i/48)+angles(i/48+.5) for i in range(48)]
data=dict(name='camp-short-step-r2',stride=STRIDE,pelvisDrop=DROP,fps=33,frames=frames)
(OUT/'camp-step.mjs').write_text('/* Generated by tools/art/camp-v2/actors/build_activity.py */\nexport const CAMP_STEP = '+json.dumps(data,separators=(',',':'))+';\n',encoding='utf8')
bpy.ops.object.select_all(action='SELECT');bpy.ops.object.delete(use_global=False)
defs=[('pelvis',-1,0,.5),('chest',0,0,.72),('neck',1,0,.86),('head',2,0,.92),('arm-left',1,-.20,.73),('arm-right',1,.20,.73),('thigh-left',0,-.085,.5),('knee-left',6,-.085,.27),('ankle-left',7,-.085,.06),('thigh-right',0,.085,.5),('knee-right',9,.085,.27),('ankle-right',10,.085,.06)]
def weights(x,h):
    if h<.51:
        r=clamp((x/H+.055)/.11);leg=clamp((.51-h)/.12);u=6;l=7;t=clamp((.32-h)/.10)
        if h<.15:u=7;l=8;t=clamp((.15-h)/.07)
        e=[(0,1-leg),(u,leg*(1-r)*(1-t)),(l,leg*(1-r)*t),(u+3,leg*r*(1-t)),(l+3,leg*r*t)]
        e=sorted([v for v in e if v[1]>0],key=lambda v:-v[1])[:4];s=sum(v[1] for v in e)
        return [(i,w/s) for i,w in e]
    j=0;t=0
    if h>.84:j=3;t=clamp((h-.84)/.05)
    elif abs(x)>H*.19 and .40<h<.82:j=4 if x<0 else 5;t=clamp((abs(x)/H-.16)/.08)
    elif h>.55:j=1;t=clamp((h-.55)/.13)
    return [(0,1-t),(j,t)]
assets=[('N01','progression-quests/N01-original.glb'),('N03','progression-quests/N03-original.glb'),('N04','progression-quests/N04-original.glb'),('N05','progression-quests/N05-original.glb'),('SuHe','foundation/su-he-v1.glb')]
for ai,(name,path) in enumerate(assets):
    before=set(bpy.data.objects);bpy.ops.import_scene.gltf(filepath=str(ROOT/'playable/assets'/path));new=set(bpy.data.objects)-before
    bpy.context.view_layer.update()
    # Blender's glTF armature importer also creates a hidden Icosphere bone shape.
    meshes=[o for o in new if o.type=='MESH' and (name!='SuHe' or o.name.startswith('su-he-surface'))];coords=[o.matrix_world@v.co for o in meshes for v in o.data.vertices]
    lo=Vector(tuple(min(v[k] for v in coords) for k in range(3)));hi=Vector(tuple(max(v[k] for v in coords) for k in range(3)));s=H/(hi.z-lo.z);c=(lo+hi)*.5;c.z=lo.z
    for o in meshes:
        matrix=o.matrix_world.copy();o.parent=None;o.matrix_world.identity();o.animation_data_clear()
        if o.data.shape_keys:o.shape_key_clear()
        for mod in list(o.modifiers):o.modifiers.remove(mod)
        for v in o.data.vertices:v.co=(matrix@v.co-c)*s
        o.vertex_groups.clear()
    for o in new:
        if o not in meshes:bpy.data.objects.remove(o,do_unlink=True)
    arm=bpy.data.armatures.new(name+'-activity');rig=bpy.data.objects.new(name+'-activity',arm);bpy.context.collection.objects.link(rig);bpy.context.view_layer.objects.active=rig;rig.select_set(True)
    bpy.ops.object.mode_set(mode='EDIT')
    for i,(n,p,x,y) in enumerate(defs):
        b=arm.edit_bones.new(n);b.head=(x*H,0,y*H);b.tail=b.head+Vector((0,0,.06));
        if p>=0:b.parent=arm.edit_bones[defs[p][0]]
    bpy.ops.object.mode_set(mode='OBJECT')
    for o in meshes:
        groups=[o.vertex_groups.new(name=d[0]) for d in defs]
        for v in o.data.vertices:
            for j,w in weights(v.co.x,v.co.z/H):
                if w:groups[j].add([v.index],w,'ADD')
        mod=o.modifiers.new('Runtime matching skin','ARMATURE');mod.object=rig;o.parent=rig;o.matrix_parent_inverse.identity();o.matrix_basis.identity()
    for f in range(49):
        frame=frames[f%48]
        for k in range(6):
            bone=rig.pose.bones[defs[6+k][0]];bone.rotation_mode='XYZ';bone.rotation_euler.x=frame[k];bone.keyframe_insert('rotation_euler',frame=f+1)
        # Root bone local Y follows Blender world Z.
        rig.pose.bones['pelvis'].location.y=-DROP;rig.pose.bones['pelvis'].keyframe_insert('location',frame=f+1)
    rig.animation_data.action.name=name+'-ShortStep-0.22mps'
    rig.location.x=(ai-2)*1.0
scene=bpy.context.scene;scene.frame_start=1;scene.frame_end=49;scene.render.fps=33;scene.frame_set(13)
bpy.ops.mesh.primitive_plane_add(size=200,location=(0,0,-.012));ground=bpy.context.object;ground.name='Preview floor'
mat=bpy.data.materials.new('Preview dark floor');mat.diffuse_color=(.035,.05,.07,1);ground.data.materials.append(mat)
world=scene.world or bpy.data.worlds.new('World');scene.world=world;world.use_nodes=True;world.node_tree.nodes['Background'].inputs[0].default_value=(.18,.23,.3,1);world.node_tree.nodes['Background'].inputs[1].default_value=.5
for loc,power,size in [((1,-4,6),1300,5),((-4,1,3),1000,4)]:
    bpy.ops.object.light_add(type='AREA',location=loc);lamp=bpy.context.object;lamp.data.energy=power;lamp.data.shape='DISK';lamp.data.size=size;lamp.rotation_euler=(Vector((0,0,1))-lamp.location).to_track_quat('-Z','Y').to_euler()
bpy.ops.object.camera_add(location=(3,-9,3));cam=bpy.context.object;cam.rotation_euler=(Vector((0,0,.85))-cam.location).to_track_quat('-Z','Y').to_euler();cam.data.type='ORTHO';cam.data.ortho_scale=6.0;scene.camera=cam
scene.render.engine='CYCLES';scene.cycles.samples=12;scene.cycles.device='CPU';scene.render.resolution_x=1200;scene.render.resolution_y=620;scene.render.resolution_percentage=100
scene.render.image_settings.file_format='PNG';scene.render.filepath=str(DOC/'short-step-preview.png')
bpy.ops.wm.save_as_mainfile(filepath=str(OUT/'npc-activity-source.blend'))
bpy.ops.render.render(write_still=True)
print('NPC_ACTIVITY_COMPLETE',str(OUT))
