import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {NPCS,TRIAL_NODES} from './data.mjs';
import {NPC_ASSETS} from './assets.mjs';
import {createNPCRig} from './npc-rig.mjs';
import {terrainHeight as defaultHeight,supportHeight} from '../layout.mjs';
import {installCampCollision} from '../foundation/camp-collision.mjs';
import {createCampActivity,installCampActorCollision} from '../camp-v2/activity.mjs';
const angle=x=>Math.atan2(Math.sin(x),Math.cos(x));
export function createProgressionScene({scene,terrainHeight=defaultHeight,assets=NPC_ASSETS,loadAsset,onChange=()=>{}}){
 const root=new THREE.Group();root.name='progression-camp';scene.add(root);const npcs=new Map(),nodes=new Map(),collisions=[],ownedLabels=[],states={};let disposed=false,time=0;
 function collision(object){const handle=installCampCollision([object]);handle.setEnabled(root.visible);collisions.push(handle);}
 function label(text,y,parent){if(!globalThis.document)return;const canvas=document.createElement('canvas');canvas.width=512;canvas.height=112;const ctx=canvas.getContext('2d');ctx.fillStyle='#0b1a24db';ctx.fillRect(0,0,512,112);ctx.fillStyle='#e2f7f8';let font=54;do{ctx.font=`bold ${font}px "Microsoft YaHei",sans-serif`;if(!ctx.measureText||ctx.measureText(text).width<=480)break;font-=2;}while(font>38);ctx.textAlign='center';ctx.fillText(text,256,75);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;const material=new THREE.SpriteMaterial({map:texture,depthTest:true,sizeAttenuation:false});const sprite=new THREE.Sprite(material);sprite.position.y=y;const viewportScale=900/(globalThis.window?.innerHeight||900);sprite.scale.set(.155*viewportScale,.032*viewportScale,1);sprite.visible=false;parent.add(sprite);ownedLabels.push({sprite,texture,material,parent});}
 // Reuse authored original relay devices. No new primitive stand-in is invented.
 for(const def of TRIAL_NODES){const original=scene.getObjectByName('relay-'+def.tuning);if(!original){states[def.id]={status:'missing-original-device'};continue;}
    const device=original.clone(true);device.name=def.id;device.position.set(def.x,terrainHeight(def.x,def.z),def.z);device.rotation.set(0,0,0);device.visible=true;root.add(device);collision(device);label(`${def.name} · F观测`,2.1,device);nodes.set(def.id,{device,def});states[def.id]={status:'ready',source:'relay-'+def.tuning};
 }
 async function load(id){const def=NPCS.find(n=>n.id===id),asset=assets[id];if(!def||disposed)return;
   if(asset?.status!=='ready'||!asset.url){states[id]={status:'awaiting-asset'};onChange();return;}
   if(npcs.has(id))return;states[id]={status:'loading'};onChange();
   try{let gltf;if(loadAsset)gltf=await loadAsset(asset.url,id);else {if(!/^[a-f0-9]{64}$/i.test(asset.sha256||''))throw Error('NPC缺少已验证SHA256');const response=await fetch(asset.url);if(!response.ok)throw Error(`NPC HTTP ${response.status}`);const bytes=await response.arrayBuffer();const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');if(hash!==asset.sha256.toLowerCase())throw Error('NPC模型SHA256不匹配');gltf=await new GLTFLoader().parseAsync(bytes,new URL('.',new URL(asset.url,document.baseURI)).href);}
      if(disposed)return;const rig=createNPCRig(gltf,{height:asset.height||1.78}),activity=createCampActivity(id);rig.root.name=id;rig.root.position.set(def.x,terrainHeight(def.x,def.z),def.z);rig.root.rotation.y=asset.yaw??Math.PI;root.add(rig.root);rig.root.updateMatrixWorld(true);rig.skeleton.update();collisions.push(installCampActorCollision(()=>activity.position));label(`${def.name} · F交谈`,2.18,rig.root);npcs.set(id,{def,rig,activity,yaw:rig.root.rotation.y});states[id]={status:'ready',vertices:rig.vertices,rig:'local-skin-with-legged-step'};
   }catch(error){states[id]={status:'failed',error:error.message};}onChange();
 }
 const ready=Promise.all(NPCS.map(n=>load(n.id)));
  function update({dt=0,player,talkingNpc=null,visible=true}={}){if(root.visible!==visible){root.visible=visible;for(const c of collisions)c.setEnabled(visible);onChange();}if(!visible)return;const dialogOpen=!!globalThis.document?.body?.classList?.contains('quest-dialog-open')||!!globalThis.document?.body?.classList?.contains('camp-dialog-open');const labelPoint=new THREE.Vector3(),viewportScale=900/(globalThis.window?.innerHeight||900);let labelChanged=false;for(const l of ownedLabels){l.parent.getWorldPosition(labelPoint);const shouldShow=!dialogOpen&&!!player&&Math.hypot(player.x-labelPoint.x,player.z-labelPoint.z)<=11;if(Math.abs(l.sprite.scale.x-.155*viewportScale)>.0001){l.sprite.scale.set(.155*viewportScale,.032*viewportScale,1);labelChanged=true;}if(l.sprite.visible!==shouldShow){l.sprite.visible=shouldShow;labelChanged=true;}}if(labelChanged)onChange();time+=Math.max(0,Math.min(dt,.1));let animated=false;for(const [id,n] of npcs){const before={...n.activity.position},position=n.activity.update(dt,{player,paused:dialogOpen||!!talkingNpc,ground:(x,z)=>supportHeight(x,z,0,terrainHeight(x,z)+1.15)});const distance=Math.hypot(position.x-before.x,position.z-before.z),speed=dt>0?distance/dt:0;let turn=0;if(distance>.0001){const nextYaw=Math.atan2(position.x-before.x,position.z-before.z),change=angle(nextYaw-n.rig.root.rotation.y),step=Math.sign(change)*Math.min(Math.abs(change),Math.max(0,dt)*2.4);n.rig.root.rotation.y+=step;turn=dt>0?step/dt:0;}n.rig.root.position.set(position.x,position.y,position.z);const near=player&&Math.hypot(player.x-position.x,player.z-position.z)<8;const yaw=near?angle(Math.atan2(player.x-position.x,player.z-position.z)-n.rig.root.rotation.y):Math.sin(time*.2)*.1;n.rig.update({dt,time,speed,turn,working:speed<.01&&Math.hypot(position.x-n.activity.target.x,position.z-n.activity.target.z)<.12,lookYaw:yaw,talking:talkingNpc===id});animated=animated||dt>0||distance>.001||Math.abs(position.y-before.y)>.001;}if(animated)onChange({dynamic:true});}
  function dispose(){disposed=true;root.removeFromParent();for(const c of collisions)c.destroy();for(const n of npcs.values())n.rig.dispose();for(const l of ownedLabels){l.texture.dispose();l.material.dispose();}npcs.clear();nodes.clear();onChange();}
  return {root,ready,load,update,dispose,position:id=>{const n=npcs.get(id);return n?{id,x:n.activity.position.x,z:n.activity.position.z,y:n.activity.position.y,radius:n.def.radius}:null;},points:mentor=>[...NPCS.filter(n=>npcs.has(n.id)).map(n=>({...n,...npcs.get(n.id).activity.position})),...(mentor?TRIAL_NODES.filter(n=>nodes.has(n.id)):[])].map(n=>({...n,type:'anomaly'})),npcReady:id=>states[id]?.status==='ready'&&npcs.has(id),nodeReady:id=>states[id]?.status==='ready'&&nodes.has(id),snapshot:()=>({states:structuredClone(states),solids:[],meshColliderCount:collisions.length,npcs:Object.fromEntries([...npcs].map(([id,n])=>[id,{...n.rig.snapshot(),position:{...n.activity.position}}]))})};
}
