import {NPCS,TRIAL_NODES} from './data.mjs';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
/** Shared NPC panel. All buttons request validated actions; rendering never mutates progress. */
export function createQuestPanel({onAction,onClose,onStorage=()=>{}}){
 const style=document.createElement('style');style.textContent=`.quest-panel{position:fixed;z-index:65;left:50%;top:50%;transform:translate(-50%,-50%);width:min(720px,calc(100vw - 32px));max-height:min(640px,calc(100vh - 36px));max-height:min(640px,calc(100dvh - 36px));display:flex;flex-direction:column;overflow:hidden;background:#111c27f5;color:#ecf3f6;border:1px solid #607b8d;border-radius:14px;box-shadow:0 18px 70px #000b;box-sizing:border-box;font:15px/1.65 "Microsoft YaHei","PingFang SC",system-ui,sans-serif}.quest-panel[hidden]{display:none}.quest-panel .quest-header{display:flex;align-items:center;justify-content:space-between;gap:16px;flex:none;padding:14px 18px;border-bottom:1px solid #435a68}.quest-panel h2{margin:0;font-size:21px;line-height:1.45;min-width:0}.quest-panel .quest-body{min-height:0;overflow-y:auto;overscroll-behavior:contain;padding:12px 18px 18px;scrollbar-width:thin}.quest-panel p{margin:8px 0;overflow-wrap:anywhere}.quest-panel button{font:inherit;color:inherit;background:#263a49;border:1px solid #7690a0;border-radius:7px;min-height:44px;padding:9px 14px;white-space:normal;text-align:left;cursor:pointer;overflow-wrap:anywhere}.quest-panel button:disabled{opacity:.45;cursor:default}.quest-panel button:focus-visible{outline:2px solid #a1fff0;outline-offset:2px}.quest-panel .choices{display:flex;gap:8px;flex-wrap:wrap}.quest-panel article{border-top:1px solid #344a59;padding:12px 0}.quest-panel .status{color:#9bced2}.quest-panel .close{flex:none}.quest-panel .quest-lead{margin-top:0}@media(max-width:680px){.quest-panel{width:calc(100vw - 16px);max-height:calc(100vh - 16px);max-height:calc(100dvh - 16px);font-size:14px}.quest-panel .quest-header{padding:9px 12px}.quest-panel h2{font-size:17px}.quest-panel .quest-body{padding:8px 12px 14px}.quest-panel .choices button{width:100%}}`;
 document.head.append(style);const el=document.createElement('section');el.className='quest-panel';el.hidden=true;el.setAttribute('role','dialog');el.setAttribute('aria-label','营地交谈');document.body.append(el);
 let npcId=null,view=null,confirm=null;
 const button=(label,action,disabled=false)=>`<button data-act="${esc(action)}" ${disabled?'disabled':''}>${esc(label)}</button>`;
 function render(){if(!npcId||!view){el.hidden=true;document.body.classList.remove('quest-dialog-open');return;}const npc=NPCS.find(n=>n.id===npcId);if(!npc||view.nearNpc!==npcId){close();return;}el.hidden=false;document.body.classList.add('quest-dialog-open');
 const bodyScroll=el.querySelector('.quest-body')?.scrollTop||0,hadConfirm=!!el.querySelector('[data-act="confirm"]');
 let content=`<p class="quest-lead">${esc(npc.text)}</p><p class="status">${esc(view.realmName)} ${view.level}级 · 修为 ${view.xp}/${view.required} · 碎灵石 ${view.coins}</p>`;
 for(const q of view.quests.filter(q=>q.npc===npcId)){content+=`<article><strong>${esc(q.name)}</strong><p>${esc(q.description)}</p><p>奖励：修为 ${q.xp} / 碎灵石 ${q.coins}</p><div class="choices">${q.status==='claimed'?'已交付，奖励已保存':q.status==='active'?button('交付并领取奖励','deliver:'+q.id,!q.ready):button('接受任务','accept:'+q.id,!q.available)}</div></article>`;}
 if(npcId==='N03')content+=`<article><p>铁陨材 ${view.iron} · 精炼铁陨 ${view.refined}</p>${button('精炼：2铁陨材 → 1精炼铁陨','refine',view.iron<2||!view.quests.some(q=>q.id==='Q02'&&q.status==='claimed'))}<p>武器和飞行器工坊尚未接通，当前只提供真实材料精炼。</p></article>`;
 if(npcId==='N04')content+=`<article><p>1下品灵石 = 100碎灵石 · 持有下品灵石 ${view.stones}</p><div class="choices">${button('兑换1下品灵石（100碎）','exchange:up',view.coins<100)}${button('兑换100碎灵石（1下品）','exchange:down',view.stones<1)}${button('打开实际营地仓库','storage')}</div></article>`;
 if(npcId==='N05'){const trained=view.quests.some(q=>q.id==='Q04'&&q.status==='claimed');content+=`<article><p>在线基础 ${20*4**view.realm}修为/小时；离线50%，最多72小时。本次基础导引免费，不自动花灵石。</p><div class="choices">${view.training?button('停止并保存结算','train-stop'):button('开始在线打坐','train-start:online',!trained)+button('开始离线保底修炼','train-start:offline',!trained)}</div>${view.trainingReport?`<p>上次结算：${view.trainingReport.gained}修为，${esc(view.trainingReport.reason)}，花石0。</p>`:''}<p>引息归环：${view.trial.nodes.length}/3 节点已稳定。到营地外三个导引节点读数，调谐后原地稳定8秒，每处消耗20电容。</p><div class="choices">${button('复核三处导引记录','calibrate',view.trial.nodes.length!==3)}${button('预览先天突破','preview',!view.canBreakthrough)}</div></article>`;}
 if(npcId==='N04'&&view.market)content+=`<article><p>本轮收购余额：${view.market.budget}碎灵石</p><div class="choices">${view.market.shop.map(o=>button(`购买${o.name} · ${o.price}碎 · 库存${o.stock}`,'buy:'+o.id,!o.stock||view.coins<o.price)).join('')}${view.market.buyback.map(o=>button(`出售${o.name} · ${o.price}碎 · 持有${o.owned}`,'sell:'+o.id,!o.owned||view.market.budget<o.price)).join('')}${button('出售1精炼铁陨 · 10碎','sell-refined',!view.refined||view.market.budget<10)}</div></article>`;
 if(confirm)content+=`<article><strong>确认操作</strong><p>${esc(confirm.text)}</p><div class="choices">${button('确认提交','confirm')}${button('返回，不提交','cancel')}</div></article>`;
 if(view.error)content+=`<p role="status">${esc(view.error)}</p>`;const html=`<header class="quest-header"><h2>${esc(npc.name)} · ${esc(npc.role)}</h2><button class="close" data-act="close">离开 · Esc</button></header><div class="quest-body">${content}</div>`;
 if(el.dataset.content!==html){el.innerHTML=html;el.dataset.content=html;const body=el.querySelector('.quest-body');body.scrollTop=confirm&&!hadConfirm?body.scrollHeight:bodyScroll;if(confirm&&!hadConfirm)el.querySelector('[data-act="confirm"]')?.focus({preventScroll:true});}
 }
 function close(){npcId=null;confirm=null;el.hidden=true;document.body.classList.remove('quest-dialog-open');onClose();}
 el.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||b.disabled)return;const [action,arg]=b.dataset.act.split(':');
  if(action==='close')return close();if(action==='cancel'){confirm=null;render();return;}if(action==='storage'){close();onStorage();return;}
  if(action==='preview'){confirm={text:'后天十级满修为 → 先天一级；已验证引息归环。解锁出生星常规大气呼吸；真空、深水仍需防护。当前不授予飞行。',payload:{action:'breakthrough',npc:npcId}};render();return;}
  if(action==='confirm'){const a=confirm?.payload;confirm=null;if(a)await onAction(a);render();return;}
  const payload={action,npc:npcId,...(['accept','deliver'].includes(action)?{quest:arg}:['buy','sell'].includes(action)?{item:arg}:action==='exchange'?{direction:arg}:action==='train-start'?{mode:arg}:{})};
  if(['deliver','refine','exchange','buy','sell','sell-refined'].includes(action)){confirm={text:b.textContent,payload};render();}else await onAction(payload);
 });
 const key=e=>{if(!el.hidden&&e.code==='Escape'){e.preventDefault();e.stopImmediatePropagation();if(confirm){confirm=null;render();}else close();}};window.addEventListener('keydown',key,true);
 return {open(id){npcId=id;confirm=null;render();},update(next){view=next;render();},close,get isOpen(){return !el.hidden;},destroy(){window.removeEventListener('keydown',key,true);document.body.classList.remove('quest-dialog-open');el.remove();style.remove();}};
}
export function trialPrompt(view){const node=TRIAL_NODES.find(n=>n.id===view.nearNode);return node?{node:node.id,text:`${node.name} · 读数 ${node.tuning} · 调谐后原地稳定8秒（20电容）`,tuning:node.tuning}:null;}
